language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"

install:
  - pip install -U pytest>=4.6.0
  - pip install pytest-cov codecov pyfakefs pytest-asyncio
  - pip install .
script:
  - pytest
after_success:
  - codecov
