# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import buffer_pb2 as buffer__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in buffer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RemoteBufferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.allocate = channel.unary_unary(
                '/buffer.RemoteBuffer/allocate',
                request_serializer=buffer__pb2.AllocateRequest.SerializeToString,
                response_deserializer=buffer__pb2.AllocateResponse.FromString,
                _registered_method=True)
        self.write = channel.stream_unary(
                '/buffer.RemoteBuffer/write',
                request_serializer=buffer__pb2.BufferWriteRequest.SerializeToString,
                response_deserializer=buffer__pb2.BufferWriteResponse.FromString,
                _registered_method=True)
        self.read = channel.unary_stream(
                '/buffer.RemoteBuffer/read',
                request_serializer=buffer__pb2.BufferReadRequest.SerializeToString,
                response_deserializer=buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.freebuffer = channel.unary_unary(
                '/buffer.RemoteBuffer/freebuffer',
                request_serializer=buffer__pb2.FreeBufferRequest.SerializeToString,
                response_deserializer=buffer__pb2.FreeBufferResponse.FromString,
                _registered_method=True)
        self.flush = channel.unary_unary(
                '/buffer.RemoteBuffer/flush',
                request_serializer=buffer__pb2.FlushRequest.SerializeToString,
                response_deserializer=buffer__pb2.FlushResponse.FromString,
                _registered_method=True)
        self.invalidate = channel.unary_unary(
                '/buffer.RemoteBuffer/invalidate',
                request_serializer=buffer__pb2.InvalidateRequest.SerializeToString,
                response_deserializer=buffer__pb2.InvalidateResponse.FromString,
                _registered_method=True)
        self.physical_address = channel.unary_unary(
                '/buffer.RemoteBuffer/physical_address',
                request_serializer=buffer__pb2.AddressRequest.SerializeToString,
                response_deserializer=buffer__pb2.AddressResponse.FromString,
                _registered_method=True)
        self.virtual_address = channel.unary_unary(
                '/buffer.RemoteBuffer/virtual_address',
                request_serializer=buffer__pb2.AddressRequest.SerializeToString,
                response_deserializer=buffer__pb2.AddressResponse.FromString,
                _registered_method=True)
        self.cacheable = channel.unary_unary(
                '/buffer.RemoteBuffer/cacheable',
                request_serializer=buffer__pb2.CacheableRequest.SerializeToString,
                response_deserializer=buffer__pb2.CacheableResponse.FromString,
                _registered_method=True)


class RemoteBufferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def allocate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def write(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def freebuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def invalidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def physical_address(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def virtual_address(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cacheable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteBufferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'allocate': grpc.unary_unary_rpc_method_handler(
                    servicer.allocate,
                    request_deserializer=buffer__pb2.AllocateRequest.FromString,
                    response_serializer=buffer__pb2.AllocateResponse.SerializeToString,
            ),
            'write': grpc.stream_unary_rpc_method_handler(
                    servicer.write,
                    request_deserializer=buffer__pb2.BufferWriteRequest.FromString,
                    response_serializer=buffer__pb2.BufferWriteResponse.SerializeToString,
            ),
            'read': grpc.unary_stream_rpc_method_handler(
                    servicer.read,
                    request_deserializer=buffer__pb2.BufferReadRequest.FromString,
                    response_serializer=buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'freebuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.freebuffer,
                    request_deserializer=buffer__pb2.FreeBufferRequest.FromString,
                    response_serializer=buffer__pb2.FreeBufferResponse.SerializeToString,
            ),
            'flush': grpc.unary_unary_rpc_method_handler(
                    servicer.flush,
                    request_deserializer=buffer__pb2.FlushRequest.FromString,
                    response_serializer=buffer__pb2.FlushResponse.SerializeToString,
            ),
            'invalidate': grpc.unary_unary_rpc_method_handler(
                    servicer.invalidate,
                    request_deserializer=buffer__pb2.InvalidateRequest.FromString,
                    response_serializer=buffer__pb2.InvalidateResponse.SerializeToString,
            ),
            'physical_address': grpc.unary_unary_rpc_method_handler(
                    servicer.physical_address,
                    request_deserializer=buffer__pb2.AddressRequest.FromString,
                    response_serializer=buffer__pb2.AddressResponse.SerializeToString,
            ),
            'virtual_address': grpc.unary_unary_rpc_method_handler(
                    servicer.virtual_address,
                    request_deserializer=buffer__pb2.AddressRequest.FromString,
                    response_serializer=buffer__pb2.AddressResponse.SerializeToString,
            ),
            'cacheable': grpc.unary_unary_rpc_method_handler(
                    servicer.cacheable,
                    request_deserializer=buffer__pb2.CacheableRequest.FromString,
                    response_serializer=buffer__pb2.CacheableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buffer.RemoteBuffer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buffer.RemoteBuffer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteBuffer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def allocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/allocate',
            buffer__pb2.AllocateRequest.SerializeToString,
            buffer__pb2.AllocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/buffer.RemoteBuffer/write',
            buffer__pb2.BufferWriteRequest.SerializeToString,
            buffer__pb2.BufferWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/buffer.RemoteBuffer/read',
            buffer__pb2.BufferReadRequest.SerializeToString,
            buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def freebuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/freebuffer',
            buffer__pb2.FreeBufferRequest.SerializeToString,
            buffer__pb2.FreeBufferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/flush',
            buffer__pb2.FlushRequest.SerializeToString,
            buffer__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def invalidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/invalidate',
            buffer__pb2.InvalidateRequest.SerializeToString,
            buffer__pb2.InvalidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def physical_address(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/physical_address',
            buffer__pb2.AddressRequest.SerializeToString,
            buffer__pb2.AddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def virtual_address(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/virtual_address',
            buffer__pb2.AddressRequest.SerializeToString,
            buffer__pb2.AddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cacheable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.RemoteBuffer/cacheable',
            buffer__pb2.CacheableRequest.SerializeToString,
            buffer__pb2.CacheableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
