# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import gpio_pb2 as gpio__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gpio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GpioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_gpio = channel.unary_unary(
                '/gpio.Gpio/get_gpio',
                request_serializer=gpio__pb2.GetGpioRequest.SerializeToString,
                response_deserializer=gpio__pb2.GetGpioResponse.FromString,
                _registered_method=True)
        self.read = channel.unary_unary(
                '/gpio.Gpio/read',
                request_serializer=gpio__pb2.GpioReadRequest.SerializeToString,
                response_deserializer=gpio__pb2.GpioReadResponse.FromString,
                _registered_method=True)
        self.write = channel.unary_unary(
                '/gpio.Gpio/write',
                request_serializer=gpio__pb2.GpioWriteRequest.SerializeToString,
                response_deserializer=gpio__pb2.GpioWriteResponse.FromString,
                _registered_method=True)
        self.unexport = channel.unary_unary(
                '/gpio.Gpio/unexport',
                request_serializer=gpio__pb2.GpioUnexportRequest.SerializeToString,
                response_deserializer=gpio__pb2.GpioUnexportResponse.FromString,
                _registered_method=True)
        self.is_exported = channel.unary_unary(
                '/gpio.Gpio/is_exported',
                request_serializer=gpio__pb2.GpioIsExportedRequest.SerializeToString,
                response_deserializer=gpio__pb2.GpioIsExportedResponse.FromString,
                _registered_method=True)
        self.get_gpio_base_path = channel.unary_unary(
                '/gpio.Gpio/get_gpio_base_path',
                request_serializer=gpio__pb2.GetGpioBasePathRequest.SerializeToString,
                response_deserializer=gpio__pb2.GetGpioBasePathResponse.FromString,
                _registered_method=True)
        self.get_gpio_npins = channel.unary_unary(
                '/gpio.Gpio/get_gpio_npins',
                request_serializer=gpio__pb2.GetGpioNPinsRequest.SerializeToString,
                response_deserializer=gpio__pb2.GetGpioNPinsResponse.FromString,
                _registered_method=True)


class GpioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_gpio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unexport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_exported(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_gpio_base_path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_gpio_npins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_gpio': grpc.unary_unary_rpc_method_handler(
                    servicer.get_gpio,
                    request_deserializer=gpio__pb2.GetGpioRequest.FromString,
                    response_serializer=gpio__pb2.GetGpioResponse.SerializeToString,
            ),
            'read': grpc.unary_unary_rpc_method_handler(
                    servicer.read,
                    request_deserializer=gpio__pb2.GpioReadRequest.FromString,
                    response_serializer=gpio__pb2.GpioReadResponse.SerializeToString,
            ),
            'write': grpc.unary_unary_rpc_method_handler(
                    servicer.write,
                    request_deserializer=gpio__pb2.GpioWriteRequest.FromString,
                    response_serializer=gpio__pb2.GpioWriteResponse.SerializeToString,
            ),
            'unexport': grpc.unary_unary_rpc_method_handler(
                    servicer.unexport,
                    request_deserializer=gpio__pb2.GpioUnexportRequest.FromString,
                    response_serializer=gpio__pb2.GpioUnexportResponse.SerializeToString,
            ),
            'is_exported': grpc.unary_unary_rpc_method_handler(
                    servicer.is_exported,
                    request_deserializer=gpio__pb2.GpioIsExportedRequest.FromString,
                    response_serializer=gpio__pb2.GpioIsExportedResponse.SerializeToString,
            ),
            'get_gpio_base_path': grpc.unary_unary_rpc_method_handler(
                    servicer.get_gpio_base_path,
                    request_deserializer=gpio__pb2.GetGpioBasePathRequest.FromString,
                    response_serializer=gpio__pb2.GetGpioBasePathResponse.SerializeToString,
            ),
            'get_gpio_npins': grpc.unary_unary_rpc_method_handler(
                    servicer.get_gpio_npins,
                    request_deserializer=gpio__pb2.GetGpioNPinsRequest.FromString,
                    response_serializer=gpio__pb2.GetGpioNPinsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpio.Gpio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gpio.Gpio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gpio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_gpio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/get_gpio',
            gpio__pb2.GetGpioRequest.SerializeToString,
            gpio__pb2.GetGpioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/read',
            gpio__pb2.GpioReadRequest.SerializeToString,
            gpio__pb2.GpioReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/write',
            gpio__pb2.GpioWriteRequest.SerializeToString,
            gpio__pb2.GpioWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unexport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/unexport',
            gpio__pb2.GpioUnexportRequest.SerializeToString,
            gpio__pb2.GpioUnexportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_exported(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/is_exported',
            gpio__pb2.GpioIsExportedRequest.SerializeToString,
            gpio__pb2.GpioIsExportedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_gpio_base_path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/get_gpio_base_path',
            gpio__pb2.GetGpioBasePathRequest.SerializeToString,
            gpio__pb2.GetGpioBasePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_gpio_npins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpio.Gpio/get_gpio_npins',
            gpio__pb2.GetGpioNPinsRequest.SerializeToString,
            gpio__pb2.GetGpioNPinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
