# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import interrupt_pb2 as interrupt__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in interrupt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RemoteInterruptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_interrupt = channel.unary_unary(
                '/interrupt.RemoteInterrupt/register_interrupt',
                request_serializer=interrupt__pb2.RegisterRequest.SerializeToString,
                response_deserializer=interrupt__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.wait_for_interrupt = channel.unary_unary(
                '/interrupt.RemoteInterrupt/wait_for_interrupt',
                request_serializer=interrupt__pb2.WaitRequest.SerializeToString,
                response_deserializer=interrupt__pb2.WaitResponse.FromString,
                _registered_method=True)
        self.release_interrupt = channel.unary_unary(
                '/interrupt.RemoteInterrupt/release_interrupt',
                request_serializer=interrupt__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=interrupt__pb2.ReleaseResponse.FromString,
                _registered_method=True)


class RemoteInterruptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_interrupt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def wait_for_interrupt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def release_interrupt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteInterruptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.register_interrupt,
                    request_deserializer=interrupt__pb2.RegisterRequest.FromString,
                    response_serializer=interrupt__pb2.RegisterResponse.SerializeToString,
            ),
            'wait_for_interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.wait_for_interrupt,
                    request_deserializer=interrupt__pb2.WaitRequest.FromString,
                    response_serializer=interrupt__pb2.WaitResponse.SerializeToString,
            ),
            'release_interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.release_interrupt,
                    request_deserializer=interrupt__pb2.ReleaseRequest.FromString,
                    response_serializer=interrupt__pb2.ReleaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interrupt.RemoteInterrupt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interrupt.RemoteInterrupt', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteInterrupt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrupt.RemoteInterrupt/register_interrupt',
            interrupt__pb2.RegisterRequest.SerializeToString,
            interrupt__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def wait_for_interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrupt.RemoteInterrupt/wait_for_interrupt',
            interrupt__pb2.WaitRequest.SerializeToString,
            interrupt__pb2.WaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def release_interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interrupt.RemoteInterrupt/release_interrupt',
            interrupt__pb2.ReleaseRequest.SerializeToString,
            interrupt__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
