# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interrupt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterrupt.proto\x12\tinterrupt\"e\n\x0fRegisterRequest\x12\x10\n\x08pin_name\x18\x01 \x01(\t\x12\x11\n\tpin_index\x18\x02 \x01(\r\x12\x0f\n\x07raw_irq\x18\x03 \x01(\r\x12\x1c\n\x14\x63ontroller_phys_addr\x18\x04 \x01(\x04\"B\n\x10RegisterResponse\x12\x10\n\x03msg\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0cinterrupt_id\x18\x02 \x01(\tB\x06\n\x04_msg\"7\n\x0bWaitRequest\x12\x14\n\x0cinterrupt_id\x18\x01 \x01(\t\x12\x12\n\ntimeout_ms\x18\x02 \x01(\r\"\x85\x01\n\x0cWaitResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.interrupt.WaitResponse.Status\x12\x10\n\x03msg\x18\x02 \x01(\tH\x00\x88\x01\x01\"+\n\x06Status\x12\t\n\x05\x46IRED\x10\x00\x12\x0b\n\x07TIMEOUT\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42\x06\n\x04_msg\"&\n\x0eReleaseRequest\x12\x14\n\x0cinterrupt_id\x18\x01 \x01(\t\"+\n\x0fReleaseResponse\x12\x10\n\x03msg\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_msg2\xf9\x01\n\x0fRemoteInterrupt\x12O\n\x12register_interrupt\x12\x1a.interrupt.RegisterRequest\x1a\x1b.interrupt.RegisterResponse\"\x00\x12G\n\x12wait_for_interrupt\x12\x16.interrupt.WaitRequest\x1a\x17.interrupt.WaitResponse\"\x00\x12L\n\x11release_interrupt\x12\x19.interrupt.ReleaseRequest\x1a\x1a.interrupt.ReleaseResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interrupt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=131
  _globals['_REGISTERRESPONSE']._serialized_start=133
  _globals['_REGISTERRESPONSE']._serialized_end=199
  _globals['_WAITREQUEST']._serialized_start=201
  _globals['_WAITREQUEST']._serialized_end=256
  _globals['_WAITRESPONSE']._serialized_start=259
  _globals['_WAITRESPONSE']._serialized_end=392
  _globals['_WAITRESPONSE_STATUS']._serialized_start=341
  _globals['_WAITRESPONSE_STATUS']._serialized_end=384
  _globals['_RELEASEREQUEST']._serialized_start=394
  _globals['_RELEASEREQUEST']._serialized_end=432
  _globals['_RELEASERESPONSE']._serialized_start=434
  _globals['_RELEASERESPONSE']._serialized_end=477
  _globals['_REMOTEINTERRUPT']._serialized_start=480
  _globals['_REMOTEINTERRUPT']._serialized_end=729
# @@protoc_insertion_point(module_scope)
