# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmio.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmmio.proto\x12\x04mmio\"3\n\x0eGetMmioRequest\x12\x11\n\tbase_addr\x18\x01 \x01(\x04\x12\x0e\n\x06length\x18\x02 \x01(\x04\"]\n\x0fGetMmioResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x03msg\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07mmio_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_msgB\n\n\x08_mmio_id\"R\n\x0bReadRequest\x12\x0f\n\x07mmio_id\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x04\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x12\n\nword_order\x18\x04 \x01(\t\"T\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x03msg\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x06\n\x04_msgB\x07\n\x05_data\"=\n\x0cWriteRequest\x12\x0f\n\x07mmio_id\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"9\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x03msg\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_msg2\xa6\x01\n\x04Mmio\x12\x39\n\x08get_mmio\x12\x14.mmio.GetMmioRequest\x1a\x15.mmio.GetMmioResponse\"\x00\x12/\n\x04read\x12\x11.mmio.ReadRequest\x1a\x12.mmio.ReadResponse\"\x00\x12\x32\n\x05write\x12\x12.mmio.WriteRequest\x1a\x13.mmio.WriteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMMIOREQUEST']._serialized_start=20
  _globals['_GETMMIOREQUEST']._serialized_end=71
  _globals['_GETMMIORESPONSE']._serialized_start=73
  _globals['_GETMMIORESPONSE']._serialized_end=166
  _globals['_READREQUEST']._serialized_start=168
  _globals['_READREQUEST']._serialized_end=250
  _globals['_READRESPONSE']._serialized_start=252
  _globals['_READRESPONSE']._serialized_end=336
  _globals['_WRITEREQUEST']._serialized_start=338
  _globals['_WRITEREQUEST']._serialized_end=399
  _globals['_WRITERESPONSE']._serialized_start=401
  _globals['_WRITERESPONSE']._serialized_end=458
  _globals['_MMIO']._serialized_start=461
  _globals['_MMIO']._serialized_end=627
# @@protoc_insertion_point(module_scope)
