# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import remote_device_pb2 as remote__device__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in remote_device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RemoteDeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set_bitstream_attrs = channel.unary_unary(
                '/remote_device.RemoteDevice/set_bitstream_attrs',
                request_serializer=remote__device__pb2.SetBitstreamAttrsRequest.SerializeToString,
                response_deserializer=remote__device__pb2.SetBitstreamAttrsResponse.FromString,
                _registered_method=True)
        self.download = channel.stream_unary(
                '/remote_device.RemoteDevice/download',
                request_serializer=remote__device__pb2.DownloadRequest.SerializeToString,
                response_deserializer=remote__device__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.set_pl_clk = channel.unary_unary(
                '/remote_device.RemoteDevice/set_pl_clk',
                request_serializer=remote__device__pb2.SetPlClkRequest.SerializeToString,
                response_deserializer=remote__device__pb2.SetPlClkResponse.FromString,
                _registered_method=True)
        self.shutdown = channel.unary_unary(
                '/remote_device.RemoteDevice/shutdown',
                request_serializer=remote__device__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=remote__device__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.readfile = channel.unary_stream(
                '/remote_device.RemoteDevice/readfile',
                request_serializer=remote__device__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=remote__device__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.writefile = channel.stream_unary(
                '/remote_device.RemoteDevice/writefile',
                request_serializer=remote__device__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=remote__device__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.existsfile = channel.unary_unary(
                '/remote_device.RemoteDevice/existsfile',
                request_serializer=remote__device__pb2.ExistsFileRequest.SerializeToString,
                response_deserializer=remote__device__pb2.ExistsFileResponse.FromString,
                _registered_method=True)


class RemoteDeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set_bitstream_attrs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_pl_clk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writefile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def existsfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set_bitstream_attrs': grpc.unary_unary_rpc_method_handler(
                    servicer.set_bitstream_attrs,
                    request_deserializer=remote__device__pb2.SetBitstreamAttrsRequest.FromString,
                    response_serializer=remote__device__pb2.SetBitstreamAttrsResponse.SerializeToString,
            ),
            'download': grpc.stream_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=remote__device__pb2.DownloadRequest.FromString,
                    response_serializer=remote__device__pb2.DownloadResponse.SerializeToString,
            ),
            'set_pl_clk': grpc.unary_unary_rpc_method_handler(
                    servicer.set_pl_clk,
                    request_deserializer=remote__device__pb2.SetPlClkRequest.FromString,
                    response_serializer=remote__device__pb2.SetPlClkResponse.SerializeToString,
            ),
            'shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.shutdown,
                    request_deserializer=remote__device__pb2.ShutdownRequest.FromString,
                    response_serializer=remote__device__pb2.ShutdownResponse.SerializeToString,
            ),
            'readfile': grpc.unary_stream_rpc_method_handler(
                    servicer.readfile,
                    request_deserializer=remote__device__pb2.ReadFileRequest.FromString,
                    response_serializer=remote__device__pb2.ReadFileResponse.SerializeToString,
            ),
            'writefile': grpc.stream_unary_rpc_method_handler(
                    servicer.writefile,
                    request_deserializer=remote__device__pb2.WriteFileRequest.FromString,
                    response_serializer=remote__device__pb2.WriteFileResponse.SerializeToString,
            ),
            'existsfile': grpc.unary_unary_rpc_method_handler(
                    servicer.existsfile,
                    request_deserializer=remote__device__pb2.ExistsFileRequest.FromString,
                    response_serializer=remote__device__pb2.ExistsFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_device.RemoteDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remote_device.RemoteDevice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteDevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set_bitstream_attrs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_device.RemoteDevice/set_bitstream_attrs',
            remote__device__pb2.SetBitstreamAttrsRequest.SerializeToString,
            remote__device__pb2.SetBitstreamAttrsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def download(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/remote_device.RemoteDevice/download',
            remote__device__pb2.DownloadRequest.SerializeToString,
            remote__device__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_pl_clk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_device.RemoteDevice/set_pl_clk',
            remote__device__pb2.SetPlClkRequest.SerializeToString,
            remote__device__pb2.SetPlClkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_device.RemoteDevice/shutdown',
            remote__device__pb2.ShutdownRequest.SerializeToString,
            remote__device__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/remote_device.RemoteDevice/readfile',
            remote__device__pb2.ReadFileRequest.SerializeToString,
            remote__device__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def writefile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/remote_device.RemoteDevice/writefile',
            remote__device__pb2.WriteFileRequest.SerializeToString,
            remote__device__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def existsfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_device.RemoteDevice/existsfile',
            remote__device__pb2.ExistsFileRequest.SerializeToString,
            remote__device__pb2.ExistsFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
