# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import xrfclk_pb2 as xrfclk__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xrfclk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class XrfclkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.find_devices = channel.unary_unary(
                '/xrfclk.Xrfclk/find_devices',
                request_serializer=xrfclk__pb2.FindDevicesRequest.SerializeToString,
                response_deserializer=xrfclk__pb2.FindDevicesResponse.FromString,
                _registered_method=True)
        self.write_lmk_regs = channel.unary_unary(
                '/xrfclk.Xrfclk/write_lmk_regs',
                request_serializer=xrfclk__pb2.WriteLmkRegsRequest.SerializeToString,
                response_deserializer=xrfclk__pb2.WriteLmkRegsResponse.FromString,
                _registered_method=True)
        self.write_lmx_regs = channel.unary_unary(
                '/xrfclk.Xrfclk/write_lmx_regs',
                request_serializer=xrfclk__pb2.WriteLmxRegsRequest.SerializeToString,
                response_deserializer=xrfclk__pb2.WriteLmxRegsResponse.FromString,
                _registered_method=True)


class XrfclkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def find_devices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def write_lmk_regs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def write_lmx_regs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XrfclkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'find_devices': grpc.unary_unary_rpc_method_handler(
                    servicer.find_devices,
                    request_deserializer=xrfclk__pb2.FindDevicesRequest.FromString,
                    response_serializer=xrfclk__pb2.FindDevicesResponse.SerializeToString,
            ),
            'write_lmk_regs': grpc.unary_unary_rpc_method_handler(
                    servicer.write_lmk_regs,
                    request_deserializer=xrfclk__pb2.WriteLmkRegsRequest.FromString,
                    response_serializer=xrfclk__pb2.WriteLmkRegsResponse.SerializeToString,
            ),
            'write_lmx_regs': grpc.unary_unary_rpc_method_handler(
                    servicer.write_lmx_regs,
                    request_deserializer=xrfclk__pb2.WriteLmxRegsRequest.FromString,
                    response_serializer=xrfclk__pb2.WriteLmxRegsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrfclk.Xrfclk', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrfclk.Xrfclk', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Xrfclk(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def find_devices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrfclk.Xrfclk/find_devices',
            xrfclk__pb2.FindDevicesRequest.SerializeToString,
            xrfclk__pb2.FindDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def write_lmk_regs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrfclk.Xrfclk/write_lmk_regs',
            xrfclk__pb2.WriteLmkRegsRequest.SerializeToString,
            xrfclk__pb2.WriteLmkRegsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def write_lmx_regs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrfclk.Xrfclk/write_lmx_regs',
            xrfclk__pb2.WriteLmxRegsRequest.SerializeToString,
            xrfclk__pb2.WriteLmxRegsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
