# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xrfclk.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cxrfclk.proto\x12\x06xrfclk\"\x14\n\x12\x46indDevicesRequest\"=\n\x13\x46indDevicesResponse\x12\x12\n\nlmk_device\x18\x01 \x01(\t\x12\x12\n\nlmx_device\x18\x02 \x01(\t\"\'\n\x13WriteLmkRegsRequest\x12\x10\n\x08reg_vals\x18\x01 \x03(\r\"\x16\n\x14WriteLmkRegsResponse\"\'\n\x13WriteLmxRegsRequest\x12\x10\n\x08reg_vals\x18\x01 \x03(\r\"\x16\n\x14WriteLmxRegsResponse\"!\n\x11ProgramLmkRequest\x12\x0c\n\x04\x66req\x18\x01 \x01(\x01\"\x14\n\x12ProgramLmkResponse\"!\n\x11ProgramLmxRequest\x12\x0c\n\x04\x66req\x18\x01 \x01(\x01\"\x14\n\x12ProgramLmxResponse2\xf7\x02\n\x06Xrfclk\x12G\n\x0c\x66ind_devices\x12\x1a.xrfclk.FindDevicesRequest\x1a\x1b.xrfclk.FindDevicesResponse\x12K\n\x0ewrite_lmk_regs\x12\x1b.xrfclk.WriteLmkRegsRequest\x1a\x1c.xrfclk.WriteLmkRegsResponse\x12K\n\x0ewrite_lmx_regs\x12\x1b.xrfclk.WriteLmxRegsRequest\x1a\x1c.xrfclk.WriteLmxRegsResponse\x12\x44\n\x0bprogram_lmk\x12\x19.xrfclk.ProgramLmkRequest\x1a\x1a.xrfclk.ProgramLmkResponse\x12\x44\n\x0bprogram_lmx\x12\x19.xrfclk.ProgramLmxRequest\x1a\x1a.xrfclk.ProgramLmxResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xrfclk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDDEVICESREQUEST']._serialized_start=24
  _globals['_FINDDEVICESREQUEST']._serialized_end=44
  _globals['_FINDDEVICESRESPONSE']._serialized_start=46
  _globals['_FINDDEVICESRESPONSE']._serialized_end=107
  _globals['_WRITELMKREGSREQUEST']._serialized_start=109
  _globals['_WRITELMKREGSREQUEST']._serialized_end=148
  _globals['_WRITELMKREGSRESPONSE']._serialized_start=150
  _globals['_WRITELMKREGSRESPONSE']._serialized_end=172
  _globals['_WRITELMXREGSREQUEST']._serialized_start=174
  _globals['_WRITELMXREGSREQUEST']._serialized_end=213
  _globals['_WRITELMXREGSRESPONSE']._serialized_start=215
  _globals['_WRITELMXREGSRESPONSE']._serialized_end=237
  _globals['_PROGRAMLMKREQUEST']._serialized_start=239
  _globals['_PROGRAMLMKREQUEST']._serialized_end=272
  _globals['_PROGRAMLMKRESPONSE']._serialized_start=274
  _globals['_PROGRAMLMKRESPONSE']._serialized_end=294
  _globals['_PROGRAMLMXREQUEST']._serialized_start=296
  _globals['_PROGRAMLMXREQUEST']._serialized_end=329
  _globals['_PROGRAMLMXRESPONSE']._serialized_start=331
  _globals['_PROGRAMLMXRESPONSE']._serialized_end=351
  _globals['_XRFCLK']._serialized_start=354
  _globals['_XRFCLK']._serialized_end=729
# @@protoc_insertion_point(module_scope)
