#!/usr/bin/env bash
#
# Build the PYNQ.remote rootfs with bitbake and write a rootfs
# tarball to $REMOTE_ROOTFS_OUT. Env inputs (from the Makefile): BOARD,
# BOARD_PATH, ROOTDIR, REMOTE_ROOTFS_OUT, optional RFSoC.

set -euo pipefail

BOARD="${BOARD:?BOARD must be set}"
BOARD_PATH="${BOARD_PATH:?BOARD_PATH must be set}"
REMOTE_ROOTFS_OUT="${REMOTE_ROOTFS_OUT:?REMOTE_ROOTFS_OUT must be set}"
# Per-board device tree, kernel config, and u-boot overlay, matching the boot build.
export PYNQ_BOARD_DTSI="${BOARD_PATH}/edf_bsp/board.dtsi"
export PYNQ_BOARD_KCFG="${BOARD_PATH}/edf_bsp/kernel.cfg"
export PYNQ_BOARD_UBOOT_DIR="${BOARD_PATH}/edf_bsp/u-boot"
ROOTDIR="${ROOTDIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RFSoC="${RFSoC:-0}"
# Board-specific remote packages to install into the image. The
# Makefile passes the default packages plus the board's REMOTE_PACKAGES_<board>.
REMOTE_PACKAGES="${REMOTE_PACKAGES:-}"

if [ -f "${BOARD_PATH}/edf.env" ]; then
    # shellcheck source=/dev/null
    source "${BOARD_PATH}/edf.env"
else
    echo "ERROR: ${BOARD_PATH}/edf.env not found. Board ${BOARD} is not configured for EDF." >&2
    exit 1
fi

EDF_MANIFEST_URL="${EDF_MANIFEST_URL:-https://github.com/Xilinx/yocto-manifests.git}"
EDF_MANIFEST_TAG="${EDF_MANIFEST_TAG:-amd-edf-rel-v25.11.1}"
EDF_MANIFEST_FILE="${EDF_MANIFEST_FILE:-default-edf.xml}"
EDF_LINUX_MACHINE="${EDF_LINUX_MACHINE:-${EDF_BOOT_MACHINE:?Set EDF_BOOT_MACHINE in edf.env}}"
REMOTE_IMAGE_RECIPE="${REMOTE_IMAGE_RECIPE:-pynq-remote-image}"

EDF_CACHE="${EDF_CACHE:-${ROOTDIR}/edf-cache}"
EDF_DIR="${EDF_DIR:-${EDF_CACHE}/pynq-edf}"
SSTATE_DIR="${SSTATE_DIR:-${EDF_CACHE}/sstate}"
DL_DIR="${DL_DIR:-${EDF_CACHE}/downloads}"
META_PYNQ="${META_PYNQ:-${ROOTDIR}/boot/meta-pynq}"
BB_NUMBER_THREADS="${BB_NUMBER_THREADS:-$(nproc)}"
PARALLEL_MAKE_JOBS="${PARALLEL_MAKE_JOBS:-$(nproc)}"

echo "============================================"
echo "PYNQ.remote rootfs build (EDF/bitbake)"
echo "  Board:         ${BOARD}"
echo "  Linux machine: ${EDF_LINUX_MACHINE}"
echo "  Image recipe:  ${REMOTE_IMAGE_RECIPE}"
echo "  RFSoC:         ${RFSoC}"
echo "  Remote pkgs:   ${REMOTE_PACKAGES}"
echo "  Output:        ${REMOTE_ROOTFS_OUT}"
echo "============================================"

# Step 1: repo init + sync (no-op if the workspace is already synced).
mkdir -p "${EDF_DIR}"
cd "${EDF_DIR}"
if [ ! -d ".repo" ]; then
    repo init -u "${EDF_MANIFEST_URL}" -b "refs/tags/${EDF_MANIFEST_TAG}" \
        -m "${EDF_MANIFEST_FILE}" --depth=1
fi
sync_jobs=$(nproc); [ "${sync_jobs}" -gt 8 ] && sync_jobs=8
repo sync -j"${sync_jobs}" --force-sync

# Step 2: source the EDF build env, configure caches, add the meta-pynq layer.
set +u
# shellcheck source=/dev/null
source edf-init-build-env
set -u

localconf="${BUILDDIR:-${EDF_DIR}/build}/conf/local.conf"
if ! grep -q "PYNQ_CONF_APPLIED" "${localconf}" 2>/dev/null; then
    cat >> "${localconf}" <<EOF

# --- PYNQ build configuration (PYNQ_CONF_APPLIED) ---
SSTATE_DIR = "${SSTATE_DIR}"
DL_DIR = "${DL_DIR}"
BB_NUMBER_THREADS = "${BB_NUMBER_THREADS}"
PARALLEL_MAKE = "-j ${PARALLEL_MAKE_JOBS}"
INHERIT += "rm_work"
BBMASK += "meta-pynq/recipes-filesystem/python/python3-pynq.*\.bb"
BBMASK += "meta-pynq/recipes-core/images/petalinux-image-full\.bbappend"
EOF
fi

if [ -d "${META_PYNQ}" ]; then
    if ! bitbake-layers show-layers 2>/dev/null | grep -q "${META_PYNQ}"; then
        bitbake-layers add-layer "${META_PYNQ}"
    fi
else
    echo "  WARN: meta-pynq layer not found at ${META_PYNQ}" >&2
fi

# Board-provided EDF remote layer.
BOARD_REMOTE_LAYER="${BOARD_PATH}/edf_bsp/meta-remote"
while read -r _name _path _prio; do
    case "${_path}" in
        */edf_bsp/meta-remote)
            [ "${_path}" = "${BOARD_REMOTE_LAYER}" ] || \
                bitbake-layers remove-layer "${_path}" >/dev/null 2>&1 || true
            ;;
    esac
done < <(bitbake-layers show-layers 2>/dev/null)
if [ -d "${BOARD_REMOTE_LAYER}" ] && \
   ! bitbake-layers show-layers 2>/dev/null | grep -q "${BOARD_REMOTE_LAYER}"; then
    bitbake-layers add-layer "${BOARD_REMOTE_LAYER}"
fi

# RFSoC boards: enable the xrfdc/xrfclk services in the gRPC server and pin the
# Linux RFdc library to the active Xilinx tool release.
autoconf="${BUILDDIR:-${EDF_DIR}/build}/conf/auto.conf"
echo "# Generated by build_edf_remote_rootfs.sh; regenerated each build." > "${autoconf}"
if [ "${RFSoC}" = "1" ]; then
    cat >> "${autoconf}" <<EOF
PACKAGECONFIG:append:pn-pynq-cpp:${EDF_LINUX_MACHINE} = " rfsoc"
EOF
    cat >> "${autoconf}" <<'EOF'
PREFERRED_VERSION_librfdc = "${@(d.getVar('XILINX_RELEASE_VERSION') or 'undefined').replace('v', '')}"
EOF
fi

# Install the board's remote packages into the remote image.
if [ -n "${REMOTE_PACKAGES// /}" ]; then
    echo "IMAGE_INSTALL:append:pn-${REMOTE_IMAGE_RECIPE} = \" ${REMOTE_PACKAGES}\"" >> "${autoconf}"
fi

# Rebuild PYNQ-authored recipes + the image so source edits apply (sstate can
# otherwise reuse stale outputs). EDF_NO_CLEAN=1 skips (pure re-package).
cd "${BUILDDIR:-${EDF_DIR}/build}"
if [ "${EDF_NO_CLEAN:-0}" != "1" ]; then
    echo ""; echo "--- cleansstate PYNQ-authored recipes + ${REMOTE_IMAGE_RECIPE} ---"
    MACHINE="${EDF_LINUX_MACHINE}" bitbake -c cleansstate \
        "${REMOTE_IMAGE_RECIPE}" pynq-cpp pynq-remote-network pynq-remote-selftest || true
    if [ "${RFSoC}" = "1" ]; then
        MACHINE="${EDF_LINUX_MACHINE}" bitbake -c cleansstate xrfclk-tics 2>/dev/null || true
    fi
    MACHINE="${EDF_LINUX_MACHINE}" bitbake -c cleansstate rfclk-init 2>/dev/null || true
fi

# Step 3: bitbake the remote appliance image.
echo ""; echo "--- bitbake ${REMOTE_IMAGE_RECIPE} (MACHINE=${EDF_LINUX_MACHINE}) ---"
MACHINE="${EDF_LINUX_MACHINE}" bitbake "${REMOTE_IMAGE_RECIPE}"

# Step 4: export the rootfs tarball.
deploy="${BUILDDIR:-${EDF_DIR}/build}/tmp/deploy/images/${EDF_LINUX_MACHINE}"
tarball=$(find "${deploy}" -name "${REMOTE_IMAGE_RECIPE}-${EDF_LINUX_MACHINE}*.tar.gz" \
    -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -n1 | cut -d' ' -f2-)
if [ -z "${tarball}" ] || [ ! -f "${tarball}" ]; then
    echo "ERROR: remote rootfs tarball not found in ${deploy}" >&2
    ls -la "${deploy}" 2>/dev/null | head || true
    exit 1
fi
cp "${tarball}" "${REMOTE_ROOTFS_OUT}"
echo ""
echo "============================================"
echo "PYNQ.remote rootfs: ${REMOTE_ROOTFS_OUT}"
echo "  (from $(basename "${tarball}"))"
echo "============================================"
