#!/bin/bash

set -o errexit

repo=$1
commit=$2
directory=$3

if [ -d $directory ]; then
  if [ ! -d $directory/.git ]; then
    echo "Directory $directory exists and is not a git repository"
    exit 1
  fi
  cd $directory
  git remote set-url origin $repo
  git fetch origin
  git checkout $commit
  exit 0
fi

if [ -e $directory ]; then
  echo "$directory exists and is not a directory"
  exit 1
fi

if [[ $commit =~ ^[0-9a-zA-Z]{40}$ ]]; then
  # If we have a hash then we have to clone the whole repo
  git clone $repo $directory
  cd $directory
  git checkout $commit
else
  # For branches and tags we only need the head
  git clone --depth 1 --branch $commit $repo $directory
fi

