Section "InputDevice"
	Identifier	"System Mouse"
	Driver		"mouse"
	Option		"Device" "/dev/input/mouse0"
EndSection

Section "InputDevice"
	Identifier	"System Keyboard"
	Driver		"kbd"
	Option		"Device" "/dev/input/event0"
EndSection

Section "Device"
        Identifier      "Card0"
        Driver          "modesetting"
        Option          "kmsdev"                "/dev/dri/card0"
EndSection

Section "Screen"
        Identifier      "DefaultScreen"
        Device          "Card0"
        DefaultDepth    16
EndSection
