# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/yunq/Zybo-MiPy-20151214/XilinxPythonProject/micropython/zybo/vivado/pmod/src/constraints/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_axi_bram_ctrl_1_0/system_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_1_0 || ORIG_REF_NAME==system_axi_bram_ctrl_1_0}]

# IP: bd/system/ip/system_axi_bram_ctrl_2_0/system_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_2_0 || ORIG_REF_NAME==system_axi_bram_ctrl_2_0}]

# IP: bd/system/ip/system_axi_bram_ctrl_3_0/system_axi_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_3_0 || ORIG_REF_NAME==system_axi_bram_ctrl_3_0}]

# IP: bd/system/ip/system_axi_bram_ctrl_4_0/system_axi_bram_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_4_0 || ORIG_REF_NAME==system_axi_bram_ctrl_4_0}]

# IP: bd/system/ip/system_axi_traceBuffer_v1_0_0_0/system_axi_traceBuffer_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_traceBuffer_v1_0_0_0 || ORIG_REF_NAME==system_axi_traceBuffer_v1_0_0_0}]

# IP: bd/system/ip/system_bit8_logic_0_0/system_bit8_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bit8_logic_0_0 || ORIG_REF_NAME==system_bit8_logic_0_0}]

# IP: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}]

# IP: bd/system/ip/system_logic_1_0/system_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_0 || ORIG_REF_NAME==system_logic_1_0}]

# IP: bd/system/ip/system_mb_1_reset_0/system_mb_1_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_1_reset_0 || ORIG_REF_NAME==system_mb_1_reset_0}]

# IP: bd/system/ip/system_mb_2_reset_0/system_mb_2_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_2_reset_0 || ORIG_REF_NAME==system_mb_2_reset_0}]

# IP: bd/system/ip/system_mb_3_reset_0/system_mb_3_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_3_reset_0 || ORIG_REF_NAME==system_mb_3_reset_0}]

# IP: bd/system/ip/system_mb_4_reset_0/system_mb_4_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_4_reset_0 || ORIG_REF_NAME==system_mb_4_reset_0}]

# IP: bd/system/ip/system_mb1_PMOD_IO_Switch_IP_0/system_mb1_PMOD_IO_Switch_IP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb1_PMOD_IO_Switch_IP_0 || ORIG_REF_NAME==system_mb1_PMOD_IO_Switch_IP_0}]

# IP: bd/system/ip/system_mb1_gpio_0/system_mb1_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb1_gpio_0 || ORIG_REF_NAME==system_mb1_gpio_0}]

# IP: bd/system/ip/system_mb1_iic_0/system_mb1_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb1_iic_0 || ORIG_REF_NAME==system_mb1_iic_0}]

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}]

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}]

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0}]

# IP: bd/system/ip/system_lmb_bram_if_cntlr_0/system_lmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_mb1_spi_0/system_mb1_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb1_spi_0 || ORIG_REF_NAME==system_mb1_spi_0}]

# IP: bd/system/ip/system_mb_1_0/system_mb_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_1_0 || ORIG_REF_NAME==system_mb_1_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_0}]

# IP: bd/system/ip/system_mb2_PMOD_IO_Switch_IP_0/system_mb2_PMOD_IO_Switch_IP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb2_PMOD_IO_Switch_IP_0 || ORIG_REF_NAME==system_mb2_PMOD_IO_Switch_IP_0}]

# IP: bd/system/ip/system_mb2_gpio_0/system_mb2_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb2_gpio_0 || ORIG_REF_NAME==system_mb2_gpio_0}]

# IP: bd/system/ip/system_mb2_iic_0/system_mb2_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb2_iic_0 || ORIG_REF_NAME==system_mb2_iic_0}]

# IP: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1}]

# IP: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1}]

# IP: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_1 || ORIG_REF_NAME==system_lmb_bram_1}]

# IP: bd/system/ip/system_lmb_bram_if_cntlr_1/system_lmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_1}]

# IP: bd/system/ip/system_mb2_spi_0/system_mb2_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb2_spi_0 || ORIG_REF_NAME==system_mb2_spi_0}]

# IP: bd/system/ip/system_mb_2_0/system_mb_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_2_0 || ORIG_REF_NAME==system_mb_2_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_1/system_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_1 || ORIG_REF_NAME==system_microblaze_0_axi_periph_1}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_1/system_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_1}]

# IP: bd/system/ip/system_mb3_PMOD_IO_Switch_IP_0/system_mb3_PMOD_IO_Switch_IP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_PMOD_IO_Switch_IP_0 || ORIG_REF_NAME==system_mb3_PMOD_IO_Switch_IP_0}]

# IP: bd/system/ip/system_mb3_gpio_0/system_mb3_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_gpio_0 || ORIG_REF_NAME==system_mb3_gpio_0}]

# IP: bd/system/ip/system_mb3_iic_0/system_mb3_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_iic_0 || ORIG_REF_NAME==system_mb3_iic_0}]

# IP: bd/system/ip/system_dlmb_v10_2/system_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_2 || ORIG_REF_NAME==system_dlmb_v10_2}]

# IP: bd/system/ip/system_ilmb_v10_2/system_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_2 || ORIG_REF_NAME==system_ilmb_v10_2}]

# IP: bd/system/ip/system_lmb_bram_2/system_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_2 || ORIG_REF_NAME==system_lmb_bram_2}]

# IP: bd/system/ip/system_lmb_bram_if_cntlr_2/system_lmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_2 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_2}]

# IP: bd/system/ip/system_mb3_spi_0/system_mb3_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_spi_0 || ORIG_REF_NAME==system_mb3_spi_0}]

# IP: bd/system/ip/system_mb_3_0/system_mb_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_3_0 || ORIG_REF_NAME==system_mb_3_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_2/system_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_2 || ORIG_REF_NAME==system_microblaze_0_axi_periph_2}]

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_2/system_rst_clk_wiz_1_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_2}]

# IP: bd/system/ip/system_mb4_PMOD_IO_Switch_IP_0/system_mb4_PMOD_IO_Switch_IP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_PMOD_IO_Switch_IP_0 || ORIG_REF_NAME==system_mb4_PMOD_IO_Switch_IP_0}]

# IP: bd/system/ip/system_mb4_gpio_0/system_mb4_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_gpio_0 || ORIG_REF_NAME==system_mb4_gpio_0}]

# IP: bd/system/ip/system_mb4_iic_0/system_mb4_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_iic_0 || ORIG_REF_NAME==system_mb4_iic_0}]

# IP: bd/system/ip/system_dlmb_v10_3/system_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_3 || ORIG_REF_NAME==system_dlmb_v10_3}]

# IP: bd/system/ip/system_ilmb_v10_3/system_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_3 || ORIG_REF_NAME==system_ilmb_v10_3}]

# IP: bd/system/ip/system_lmb_bram_3/system_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_3 || ORIG_REF_NAME==system_lmb_bram_3}]

# IP: bd/system/ip/system_lmb_bram_if_cntlr_3/system_lmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_3 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_3}]

# IP: bd/system/ip/system_mb4_spi_0/system_mb4_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_spi_0 || ORIG_REF_NAME==system_mb4_spi_0}]

# IP: bd/system/ip/system_mb_4_0/system_mb_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_4_0 || ORIG_REF_NAME==system_mb_4_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_3/system_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_3 || ORIG_REF_NAME==system_microblaze_0_axi_periph_3}]

# IP: bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3}]

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_3/system_rst_clk_wiz_1_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_3}]

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0}]

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4}]

# IP: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# IP: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}]

# IP: bd/system/ip/system_tracebuffer_sel_0/system_tracebuffer_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tracebuffer_sel_0 || ORIG_REF_NAME==system_tracebuffer_sel_0}]

# IP: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_xup_mux_data_in_0/system_xup_mux_data_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xup_mux_data_in_0 || ORIG_REF_NAME==system_xup_mux_data_in_0}]

# IP: bd/system/ip/system_xup_mux_data_out_0/system_xup_mux_data_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xup_mux_data_out_0 || ORIG_REF_NAME==system_xup_mux_data_out_0}]

# IP: bd/system/ip/system_xup_mux_tri_out_0/system_xup_mux_tri_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xup_mux_tri_out_0 || ORIG_REF_NAME==system_xup_mux_tri_out_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2}]

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3}]

# IP: bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4}]

# XDC: bd/system/ip/system_axi_bram_ctrl_1_0/system_axi_bram_ctrl_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_bram_ctrl_2_0/system_axi_bram_ctrl_2_0_ooc.xdc

# XDC: bd/system/ip/system_axi_bram_ctrl_3_0/system_axi_bram_ctrl_3_0_ooc.xdc

# XDC: bd/system/ip/system_axi_bram_ctrl_4_0/system_axi_bram_ctrl_4_0_ooc.xdc

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb1_gpio_0/system_mb1_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb1_gpio_0 || ORIG_REF_NAME==system_mb1_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb1_gpio_0/system_mb1_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_mb1_gpio_0/system_mb1_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb1_gpio_0 || ORIG_REF_NAME==system_mb1_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb1_iic_0/system_mb1_iic_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb1_iic_0 || ORIG_REF_NAME==system_mb1_iic_0}]

# XDC: bd/system/ip/system_mb1_iic_0/system_mb1_iic_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_if_cntlr_0/system_lmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_mb1_spi_0/system_mb1_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb1_spi_0 || ORIG_REF_NAME==system_mb1_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb1_spi_0/system_mb1_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb1_spi_0 || ORIG_REF_NAME==system_mb1_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb1_spi_0/system_mb1_spi_0_ooc.xdc

# XDC: bd/system/ip/system_mb1_spi_0/system_mb1_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb1_spi_0 || ORIG_REF_NAME==system_mb1_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_1_0/system_mb_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb_1_0 || ORIG_REF_NAME==system_mb_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_1_0/system_mb_1_0_ooc_debug.xdc

# XDC: bd/system/ip/system_mb_1_0/system_mb_1_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_0}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_0}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/system/ip/system_mb2_gpio_0/system_mb2_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb2_gpio_0 || ORIG_REF_NAME==system_mb2_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb2_gpio_0/system_mb2_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_mb2_gpio_0/system_mb2_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb2_gpio_0 || ORIG_REF_NAME==system_mb2_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb2_iic_0/system_mb2_iic_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb2_iic_0 || ORIG_REF_NAME==system_mb2_iic_0}]

# XDC: bd/system/ip/system_mb2_iic_0/system_mb2_iic_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_if_cntlr_1/system_lmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/system/ip/system_mb2_spi_0/system_mb2_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb2_spi_0 || ORIG_REF_NAME==system_mb2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb2_spi_0/system_mb2_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb2_spi_0 || ORIG_REF_NAME==system_mb2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb2_spi_0/system_mb2_spi_0_ooc.xdc

# XDC: bd/system/ip/system_mb2_spi_0/system_mb2_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb2_spi_0 || ORIG_REF_NAME==system_mb2_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_2_0/system_mb_2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb_2_0 || ORIG_REF_NAME==system_mb_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_2_0/system_mb_2_0_ooc_debug.xdc

# XDC: bd/system/ip/system_mb_2_0/system_mb_2_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_1/system_rst_clk_wiz_1_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_1}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_1/system_rst_clk_wiz_1_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_1}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_1/system_rst_clk_wiz_1_100M_1_ooc.xdc

# XDC: bd/system/ip/system_mb3_gpio_0/system_mb3_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb3_gpio_0 || ORIG_REF_NAME==system_mb3_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb3_gpio_0/system_mb3_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_mb3_gpio_0/system_mb3_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb3_gpio_0 || ORIG_REF_NAME==system_mb3_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb3_iic_0/system_mb3_iic_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_iic_0 || ORIG_REF_NAME==system_mb3_iic_0}]

# XDC: bd/system/ip/system_mb3_iic_0/system_mb3_iic_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_2/system_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_2 || ORIG_REF_NAME==system_dlmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_2/system_dlmb_v10_2_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_2/system_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_2 || ORIG_REF_NAME==system_ilmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_2/system_ilmb_v10_2_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_2/system_lmb_bram_2_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_if_cntlr_2/system_lmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/system/ip/system_mb3_spi_0/system_mb3_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb3_spi_0 || ORIG_REF_NAME==system_mb3_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb3_spi_0/system_mb3_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb3_spi_0 || ORIG_REF_NAME==system_mb3_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb3_spi_0/system_mb3_spi_0_ooc.xdc

# XDC: bd/system/ip/system_mb3_spi_0/system_mb3_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb3_spi_0 || ORIG_REF_NAME==system_mb3_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_3_0/system_mb_3_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb_3_0 || ORIG_REF_NAME==system_mb_3_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_3_0/system_mb_3_0_ooc_debug.xdc

# XDC: bd/system/ip/system_mb_3_0/system_mb_3_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_2/system_rst_clk_wiz_1_100M_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_2}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_2/system_rst_clk_wiz_1_100M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_2}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_2/system_rst_clk_wiz_1_100M_2_ooc.xdc

# XDC: bd/system/ip/system_mb4_gpio_0/system_mb4_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb4_gpio_0 || ORIG_REF_NAME==system_mb4_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb4_gpio_0/system_mb4_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_mb4_gpio_0/system_mb4_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb4_gpio_0 || ORIG_REF_NAME==system_mb4_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb4_iic_0/system_mb4_iic_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_iic_0 || ORIG_REF_NAME==system_mb4_iic_0}]

# XDC: bd/system/ip/system_mb4_iic_0/system_mb4_iic_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_3/system_dlmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_3 || ORIG_REF_NAME==system_dlmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_3/system_dlmb_v10_3_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_3/system_ilmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_3 || ORIG_REF_NAME==system_ilmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_3/system_ilmb_v10_3_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_3/system_lmb_bram_3_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_if_cntlr_3/system_lmb_bram_if_cntlr_3_ooc.xdc

# XDC: bd/system/ip/system_mb4_spi_0/system_mb4_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb4_spi_0 || ORIG_REF_NAME==system_mb4_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb4_spi_0/system_mb4_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb4_spi_0 || ORIG_REF_NAME==system_mb4_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb4_spi_0/system_mb4_spi_0_ooc.xdc

# XDC: bd/system/ip/system_mb4_spi_0/system_mb4_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb4_spi_0 || ORIG_REF_NAME==system_mb4_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_4_0/system_mb_4_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mb_4_0 || ORIG_REF_NAME==system_mb_4_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_4_0/system_mb_4_0_ooc_debug.xdc

# XDC: bd/system/ip/system_mb_4_0/system_mb_4_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_3/system_xbar_3_ooc.xdc

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_3/system_rst_clk_wiz_1_100M_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_3}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_3/system_rst_clk_wiz_1_100M_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_3}]

# XDC: bd/system/ip/system_rst_clk_wiz_1_100M_3/system_rst_clk_wiz_1_100M_3_ooc.xdc

# XDC: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc_trace.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_xbar_4/system_xbar_4_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc

# XDC: bd/system/system_ooc.xdc
