#ifndef APF_PERF_INSTRUMENTATION_H
#define APF_PERF_INSTRUMENTATION_H

#ifdef __cplusplus
extern "C" {
#endif

struct sw_function_perf_info_struct {
  unsigned long long cycleCount;
  unsigned int entryCount;
  int isRoot;
  char *function_name;
};

typedef struct sw_function_perf_info_struct sw_function_perf_info_t;

struct hw_cluster_perf_info_struct {
  unsigned int latency;
  unsigned int dsp;
  unsigned int bram;
  unsigned int lut;  
  unsigned int num_functions;
  unsigned int sw_latency;
  char *function_names[];
};

typedef struct hw_cluster_perf_info_struct hw_cluster_perf_info_t;

struct resources_struct {
  unsigned int dsp;
  unsigned int bram;
  unsigned int lut;
};

typedef struct resources_struct resources_t;  
  
void add_sw_perf_function(sw_function_perf_info_t *sw_function);
void add_hw_perf_cluster(hw_cluster_perf_info_t *hw_cluster);  
void apf_perf_estimation_exit(void);
void add_sw_estimates(void); //implementation generated by tools and linked in later
void add_hw_estimates(void);//implementation generated by tools and linked in later
void apf_perf_gen_report(void);
  
#ifdef __cplusplus
};
#endif
  
#endif
