#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral IOP3_MB */
#define XPAR_IOP3_MB_ADDR_SIZE 32
#define XPAR_IOP3_MB_ADDR_TAG_BITS 17
#define XPAR_IOP3_MB_ALLOW_DCACHE_WR 1
#define XPAR_IOP3_MB_ALLOW_ICACHE_WR 1
#define XPAR_IOP3_MB_AREA_OPTIMIZED 0
#define XPAR_IOP3_MB_ASYNC_INTERRUPT 1
#define XPAR_IOP3_MB_ASYNC_WAKEUP 3
#define XPAR_IOP3_MB_AVOID_PRIMITIVES 0
#define XPAR_IOP3_MB_BASE_VECTORS 0x0000000000000000
#define XPAR_IOP3_MB_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_IOP3_MB_CACHE_BYTE_SIZE 8192
#define XPAR_IOP3_MB_DADDR_SIZE 32
#define XPAR_IOP3_MB_DATA_SIZE 32
#define XPAR_IOP3_MB_DCACHE_ADDR_TAG 17
#define XPAR_IOP3_MB_DCACHE_ALWAYS_USED 0
#define XPAR_IOP3_MB_DCACHE_BASEADDR 0x00000000
#define XPAR_IOP3_MB_DCACHE_BYTE_SIZE 8192
#define XPAR_IOP3_MB_DCACHE_DATA_WIDTH 0
#define XPAR_IOP3_MB_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_IOP3_MB_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_IOP3_MB_DCACHE_LINE_LEN 4
#define XPAR_IOP3_MB_DCACHE_USE_WRITEBACK 0
#define XPAR_IOP3_MB_DCACHE_VICTIMS 0
#define XPAR_IOP3_MB_DC_AXI_MON 0
#define XPAR_IOP3_MB_DEBUG_COUNTER_WIDTH 32
#define XPAR_IOP3_MB_DEBUG_ENABLED 1
#define XPAR_IOP3_MB_DEBUG_EVENT_COUNTERS 5
#define XPAR_IOP3_MB_DEBUG_EXTERNAL_TRACE 0
#define XPAR_IOP3_MB_DEBUG_LATENCY_COUNTERS 1
#define XPAR_IOP3_MB_DEBUG_PROFILE_SIZE 0
#define XPAR_IOP3_MB_DEBUG_TRACE_SIZE 8192
#define XPAR_IOP3_MB_DIV_ZERO_EXCEPTION 0
#define XPAR_IOP3_MB_DP_AXI_MON 0
#define XPAR_IOP3_MB_DYNAMIC_BUS_SIZING 0
#define XPAR_IOP3_MB_D_AXI 1
#define XPAR_IOP3_MB_D_LMB 1
#define XPAR_IOP3_MB_D_LMB_MON 0
#define XPAR_IOP3_MB_ECC_USE_CE_EXCEPTION 0
#define XPAR_IOP3_MB_EDGE_IS_POSITIVE 1
#define XPAR_IOP3_MB_ENABLE_DISCRETE_PORTS 0
#define XPAR_IOP3_MB_ENDIANNESS 1
#define XPAR_IOP3_MB_FAULT_TOLERANT 0
#define XPAR_IOP3_MB_FPU_EXCEPTION 0
#define XPAR_IOP3_MB_FREQ 100000000
#define XPAR_IOP3_MB_FSL_EXCEPTION 0
#define XPAR_IOP3_MB_FSL_LINKS 0
#define XPAR_IOP3_MB_IADDR_SIZE 32
#define XPAR_IOP3_MB_ICACHE_ALWAYS_USED 0
#define XPAR_IOP3_MB_ICACHE_BASEADDR 0x00000000
#define XPAR_IOP3_MB_ICACHE_DATA_WIDTH 0
#define XPAR_IOP3_MB_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_IOP3_MB_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_IOP3_MB_ICACHE_LINE_LEN 4
#define XPAR_IOP3_MB_ICACHE_STREAMS 0
#define XPAR_IOP3_MB_ICACHE_VICTIMS 0
#define XPAR_IOP3_MB_IC_AXI_MON 0
#define XPAR_IOP3_MB_ILL_OPCODE_EXCEPTION 0
#define XPAR_IOP3_MB_IMPRECISE_EXCEPTIONS 0
#define XPAR_IOP3_MB_INSTR_SIZE 32
#define XPAR_IOP3_MB_INTERCONNECT 2
#define XPAR_IOP3_MB_INTERRUPT_IS_EDGE 0
#define XPAR_IOP3_MB_INTERRUPT_MON 0
#define XPAR_IOP3_MB_IP_AXI_MON 0
#define XPAR_IOP3_MB_I_AXI 0
#define XPAR_IOP3_MB_I_LMB 1
#define XPAR_IOP3_MB_I_LMB_MON 0
#define XPAR_IOP3_MB_LOCKSTEP_SELECT 0
#define XPAR_IOP3_MB_LOCKSTEP_SLAVE 0
#define XPAR_IOP3_MB_M0_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M0_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M1_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M1_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M2_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M2_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M3_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M3_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M4_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M4_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M5_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M5_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M6_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M6_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M7_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M7_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M8_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M8_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M9_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M9_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M10_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M10_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M11_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M11_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M12_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M12_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M13_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M13_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M14_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M14_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_M15_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_M15_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_MMU_DTLB_SIZE 4
#define XPAR_IOP3_MB_MMU_ITLB_SIZE 2
#define XPAR_IOP3_MB_MMU_PRIVILEGED_INSTR 0
#define XPAR_IOP3_MB_MMU_TLB_ACCESS 3
#define XPAR_IOP3_MB_MMU_ZONES 16
#define XPAR_IOP3_MB_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_IOP3_MB_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_IOP3_MB_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_DC_DATA_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_IOP3_MB_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_DC_USER_SIGNALS 0
#define XPAR_IOP3_MB_M_AXI_DC_USER_VALUE 31
#define XPAR_IOP3_MB_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_DP_DATA_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_IOP3_MB_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_IOP3_MB_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_IOP3_MB_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_IOP3_MB_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_IC_DATA_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_IC_USER_SIGNALS 0
#define XPAR_IOP3_MB_M_AXI_IC_USER_VALUE 31
#define XPAR_IOP3_MB_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_IP_DATA_WIDTH 32
#define XPAR_IOP3_MB_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_IOP3_MB_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_IOP3_MB_NUMBER_OF_PC_BRK 1
#define XPAR_IOP3_MB_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_IOP3_MB_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_IOP3_MB_NUM_SYNC_FF_CLK 2
#define XPAR_IOP3_MB_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_IOP3_MB_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_IOP3_MB_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_IOP3_MB_OPCODE_0X0_ILLEGAL 0
#define XPAR_IOP3_MB_OPTIMIZATION 0
#define XPAR_IOP3_MB_PC_WIDTH 32
#define XPAR_IOP3_MB_PVR 0
#define XPAR_IOP3_MB_PVR_USER1 0x00
#define XPAR_IOP3_MB_PVR_USER2 0x00000000
#define XPAR_IOP3_MB_RESET_MSR 0x00000000
#define XPAR_IOP3_MB_S0_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S0_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S1_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S1_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S2_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S2_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S3_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S3_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S4_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S4_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S5_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S5_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S6_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S6_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S7_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S7_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S8_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S8_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S9_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S9_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S10_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S10_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S11_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S11_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S12_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S12_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S13_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S13_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S14_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S14_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_S15_AXIS_DATA_WIDTH 32
#define XPAR_IOP3_MB_S15_AXIS_PROTOCOL GENERIC
#define XPAR_IOP3_MB_SCO 0
#define XPAR_IOP3_MB_TRACE 0
#define XPAR_IOP3_MB_UNALIGNED_EXCEPTIONS 0
#define XPAR_IOP3_MB_USE_BARREL 0
#define XPAR_IOP3_MB_USE_BRANCH_TARGET_CACHE 0
#define XPAR_IOP3_MB_USE_CONFIG_RESET 0
#define XPAR_IOP3_MB_USE_DCACHE 0
#define XPAR_IOP3_MB_USE_DIV 0
#define XPAR_IOP3_MB_USE_EXTENDED_FSL_INSTR 0
#define XPAR_IOP3_MB_USE_EXT_BRK 0
#define XPAR_IOP3_MB_USE_EXT_NM_BRK 0
#define XPAR_IOP3_MB_USE_FPU 0
#define XPAR_IOP3_MB_USE_HW_MUL 0
#define XPAR_IOP3_MB_USE_ICACHE 0
#define XPAR_IOP3_MB_USE_INTERRUPT 1
#define XPAR_IOP3_MB_USE_MMU 0
#define XPAR_IOP3_MB_USE_MSR_INSTR 0
#define XPAR_IOP3_MB_USE_NON_SECURE 0
#define XPAR_IOP3_MB_USE_PCMP_INSTR 0
#define XPAR_IOP3_MB_USE_REORDER_INSTR 1
#define XPAR_IOP3_MB_USE_STACK_PROTECTION 0
#define XPAR_IOP3_MB_COMPONENT_NAME system_mb_2
#define XPAR_IOP3_MB_EDK_IPTYPE PROCESSOR
#define XPAR_IOP3_MB_EDK_SPECIAL microblaze
#define XPAR_IOP3_MB_G_TEMPLATE_LIST 0
#define XPAR_IOP3_MB_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 2
#define XPAR_MICROBLAZE_ID 2
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 1
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME system_mb_2
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Definitions for driver ARDUINO_IO_SWITCH */
#define XPAR_ARDUINO_IO_SWITCH_NUM_INSTANCES 1

/* Definitions for peripheral IOP3_ARDUINO_IO_SWITCH_0 */
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_DEVICE_ID 0
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_S_AXI_BASEADDR 0x44A20000
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_S_AXI_HIGHADDR 0x44A2FFFF


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR */
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_DEVICE_ID 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_HIGHADDR 0x0000FFFF
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_IOP3_MB3_LMB_LMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_0_WRITE_ACCESS 2
#define XPAR_BRAM_0_BASEADDR 0x00000000
#define XPAR_BRAM_0_HIGHADDR 0x0000FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0 */
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_BASEADDR 0x40020000
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_HIGHADDR 0x4002FFFF
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_DEVICE_ID 0
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_INTERRUPT_PRESENT 0
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_IS_DUAL 1


/* Definitions for peripheral IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0 */
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_BASEADDR 0x40000000
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_HIGHADDR 0x4000FFFF
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_DEVICE_ID 1
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_INTERRUPT_PRESENT 0
#define XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_IS_DUAL 0


/* Definitions for peripheral IOP3_MB3_INTR */
#define XPAR_IOP3_MB3_INTR_BASEADDR 0x40010000
#define XPAR_IOP3_MB3_INTR_HIGHADDR 0x4001FFFF
#define XPAR_IOP3_MB3_INTR_DEVICE_ID 2
#define XPAR_IOP3_MB3_INTR_INTERRUPT_PRESENT 0
#define XPAR_IOP3_MB3_INTR_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0 */
#define XPAR_GPIO_0_BASEADDR 0x40020000
#define XPAR_GPIO_0_HIGHADDR 0x4002FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_ARDUINO_GPIO_D13_D0_A5_A0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 1

/* Canonical definitions for peripheral IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0 */
#define XPAR_GPIO_1_BASEADDR 0x40000000
#define XPAR_GPIO_1_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_IOP3_MB3_GPIO_SUBSYSTEM_MB3_CK_GPIO_D15_D0_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0

/* Canonical definitions for peripheral IOP3_MB3_INTR */
#define XPAR_GPIO_2_BASEADDR 0x40010000
#define XPAR_GPIO_2_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_IOP3_MB3_INTR_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 0


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 2

/* Definitions for peripheral IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW */
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_DEVICE_ID 0
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_BASEADDR 0x40800000
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_HIGHADDR 0x4080FFFF
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_TEN_BIT_ADR 0
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_GPO_WIDTH 1


/* Definitions for peripheral IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW */
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_DEVICE_ID 1
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_BASEADDR 0x40810000
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_HIGHADDR 0x4081FFFF
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_TEN_BIT_ADR 0
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_GPO_WIDTH 1


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW */
#define XPAR_IIC_0_DEVICE_ID XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x40800000
#define XPAR_IIC_0_HIGHADDR 0x4080FFFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1

/* Canonical definitions for peripheral IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW */
#define XPAR_IIC_1_DEVICE_ID XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_SHARED_IIC_SW_DEVICE_ID
#define XPAR_IIC_1_BASEADDR 0x40810000
#define XPAR_IIC_1_HIGHADDR 0x4081FFFF
#define XPAR_IIC_1_TEN_BIT_ADR 0
#define XPAR_IIC_1_GPO_WIDTH 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 29
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral IOP3_MB3_INTC */
#define XPAR_IOP3_MB3_INTC_DEVICE_ID 0
#define XPAR_IOP3_MB3_INTC_BASEADDR 0x41200000
#define XPAR_IOP3_MB3_INTC_HIGHADDR 0x4120FFFF
#define XPAR_IOP3_MB3_INTC_KIND_OF_INTR 0xFFFFFFFF
#define XPAR_IOP3_MB3_INTC_HAS_FAST 0
#define XPAR_IOP3_MB3_INTC_IVAR_RESET_VALUE 0x00000010
#define XPAR_IOP3_MB3_INTC_NUM_INTR_INPUTS 29


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_IOP3_MB3_INTC_DEVICE_ID
#define XPAR_IOP3_MB3_INTC_TYPE 0
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_0_MASK 0X000001
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_0_INTR 0
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_1_MASK 0X000002
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_1_INTR 1
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_2_MASK 0X000004
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_2_INTR 2
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_3_MASK 0X000008
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_3_INTR 3
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_4_MASK 0X000010
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_4_INTR 4
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_5_MASK 0X000020
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_5_INTR 5
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_0_MASK 0X000040
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_0_INTR 6
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_1_MASK 0X000080
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_1_INTR 7
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_0_MASK 0X000100
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_0_INTR 8
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_1_MASK 0X000200
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_1_INTR 9
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_2_MASK 0X000400
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_2_INTR 10
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_3_MASK 0X000800
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_3_INTR 11
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_4_MASK 0X001000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_4_INTR 12
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_5_MASK 0X002000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_5_INTR 13
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_6_MASK 0X004000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_6_INTR 14
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_7_MASK 0X008000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_7_INTR 15
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_8_MASK 0X010000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_8_INTR 16
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_9_MASK 0X020000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_9_INTR 17
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_10_MASK 0X040000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_10_INTR 18
#define XPAR_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_11_MASK 0X080000
#define XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_11_INTR 19
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_INTERRUPT_MASK 0X100000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_INTERRUPT_INTR 20
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_INTERRUPT_MASK 0X200000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_INTERRUPT_INTR 21
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_INTERRUPT_MASK 0X400000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_INTERRUPT_INTR 22
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_INTERRUPT_MASK 0X800000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_INTERRUPT_INTR 23
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_INTERRUPT_MASK 0X1000000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_INTERRUPT_INTR 24
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_INTERRUPT_MASK 0X2000000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_INTERRUPT_INTR 25
#define XPAR_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_IIC2INTC_IRPT_MASK 0X4000000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_IIC2INTC_IRPT_INTR 26
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_IP2INTC_IRPT_MASK 0X8000000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_IP2INTC_IRPT_INTR 27
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_INTERRUPT_MASK 0X10000000
#define XPAR_IOP3_MB3_INTC_IOP3_MB3_UARTLITE_D1_D0_INTERRUPT_INTR 28

/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_IOP3_MB3_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000
#define XPAR_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFF
#define XPAR_INTC_0_HAS_FAST 0
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x00000010
#define XPAR_INTC_0_NUM_INTR_INPUTS 29
#define XPAR_INTC_0_INTC_TYPE 0

#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_0_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_1_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_1_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_2_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_2_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_3_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_3_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_4_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_4_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_5_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_A5_A0_5_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_0_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_1_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D1_D0_1_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_0_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_1_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_1_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_2_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_2_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_3_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_3_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_4_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_4_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_5_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_5_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_6_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_6_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_7_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_7_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_8_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_8_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_9_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_9_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_10_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_10_INTR
#define XPAR_INTC_0_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_11_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_ARDUINO_IO_SWITCH_0_INTERRUPT_I_IN_D13_D2_11_INTR
#define XPAR_INTC_0_TMRCTR_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_1_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_2_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_3_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_4_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_5_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_INTERRUPT_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_IIC_SUBSYSTEM_MB3_IIC_PL_SW_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTLITE_0_VEC_ID XPAR_IOP3_MB3_INTC_IOP3_MB3_UARTLITE_D1_D0_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 2

/* Definitions for peripheral IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW */
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_DEVICE_ID 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_BASEADDR 0x44A10000
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_HIGHADDR 0x44A1FFFF
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_FIFO_DEPTH 16
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_FIFO_EXIST 1
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_SPI_SLAVE_ONLY 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_NUM_SS_BITS 1
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_NUM_TRANSFER_BITS 8
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_SPI_MODE 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_TYPE_OF_AXI4_INTERFACE 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_AXI4_BASEADDR 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_AXI4_HIGHADDR 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_XIP_MODE 0

/* Canonical definitions for peripheral IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW */
#define XPAR_SPI_0_DEVICE_ID 0
#define XPAR_SPI_0_BASEADDR 0x44A10000
#define XPAR_SPI_0_HIGHADDR 0x44A1FFFF
#define XPAR_SPI_0_FIFO_DEPTH 16
#define XPAR_SPI_0_FIFO_EXIST 1
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0
#define XPAR_SPI_0_NUM_SS_BITS 1
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8
#define XPAR_SPI_0_SPI_MODE 0
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0
#define XPAR_SPI_0_AXI4_BASEADDR 0
#define XPAR_SPI_0_AXI4_HIGHADDR 0
#define XPAR_SPI_0_XIP_MODE 0
#define XPAR_SPI_0_USE_STARTUP 0



/* Definitions for peripheral IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10 */
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_DEVICE_ID 1
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_BASEADDR 0x44A00000
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_HIGHADDR 0x44A0FFFF
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_FIFO_DEPTH 16
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_FIFO_EXIST 1
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_SPI_SLAVE_ONLY 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_NUM_SS_BITS 1
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_NUM_TRANSFER_BITS 8
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_SPI_MODE 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_TYPE_OF_AXI4_INTERFACE 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_AXI4_BASEADDR 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_AXI4_HIGHADDR 0
#define XPAR_IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10_XIP_MODE 0

/* Canonical definitions for peripheral IOP3_MB3_SPI_SUBSYSTEM_MB3_SPI_PL_SW_D13_D10 */
#define XPAR_SPI_1_DEVICE_ID 1
#define XPAR_SPI_1_BASEADDR 0x44A00000
#define XPAR_SPI_1_HIGHADDR 0x44A0FFFF
#define XPAR_SPI_1_FIFO_DEPTH 16
#define XPAR_SPI_1_FIFO_EXIST 1
#define XPAR_SPI_1_SPI_SLAVE_ONLY 0
#define XPAR_SPI_1_NUM_SS_BITS 1
#define XPAR_SPI_1_NUM_TRANSFER_BITS 8
#define XPAR_SPI_1_SPI_MODE 0
#define XPAR_SPI_1_TYPE_OF_AXI4_INTERFACE 0
#define XPAR_SPI_1_AXI4_BASEADDR 0
#define XPAR_SPI_1_AXI4_HIGHADDR 0
#define XPAR_SPI_1_XIP_MODE 0
#define XPAR_SPI_1_USE_STARTUP 0



/******************************************************************/

/* Definitions for driver SYSMON */
#define XPAR_XSYSMON_NUM_INSTANCES 1

/* Definitions for peripheral IOP3_MB3_XADC */
#define XPAR_IOP3_MB3_XADC_IP_TYPE 0
#define XPAR_IOP3_MB3_XADC_DEVICE_ID 0
#define XPAR_IOP3_MB3_XADC_BASEADDR 0x44A30000
#define XPAR_IOP3_MB3_XADC_HIGHADDR 0x44A3FFFF
#define XPAR_IOP3_MB3_XADC_INCLUDE_INTR 1


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_XADC */
#define XPAR_SYSMON_0_IP_TYPE 0
#define XPAR_SYSMON_0_DEVICE_ID XPAR_IOP3_MB3_XADC_DEVICE_ID
#define XPAR_SYSMON_0_BASEADDR 0x44A30000
#define XPAR_SYSMON_0_HIGHADDR 0x44A3FFFF
#define XPAR_SYSMON_0_INCLUDE_INTR 1


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 6

/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_DEVICE_ID 0
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_BASEADDR 0x41C00000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_HIGHADDR 0x41C0FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_CLOCK_FREQ_HZ 100000000


/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_DEVICE_ID 1
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_BASEADDR 0x41C10000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_HIGHADDR 0x41C1FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_CLOCK_FREQ_HZ 100000000


/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_DEVICE_ID 2
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_BASEADDR 0x41C20000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_HIGHADDR 0x41C2FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_CLOCK_FREQ_HZ 100000000


/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_DEVICE_ID 3
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_BASEADDR 0x41C30000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_HIGHADDR 0x41C3FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_CLOCK_FREQ_HZ 100000000


/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_DEVICE_ID 4
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_BASEADDR 0x41C40000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_HIGHADDR 0x41C4FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_CLOCK_FREQ_HZ 100000000


/* Definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5 */
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_DEVICE_ID 5
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_BASEADDR 0x41C50000
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_HIGHADDR 0x41C5FFFF
#define XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_CLOCK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID 0
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFF
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_0_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1 */
#define XPAR_TMRCTR_1_DEVICE_ID 0
#define XPAR_TMRCTR_1_BASEADDR 0x41C10000
#define XPAR_TMRCTR_1_HIGHADDR 0x41C1FFFF
#define XPAR_TMRCTR_1_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_1_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2 */
#define XPAR_TMRCTR_2_DEVICE_ID 0
#define XPAR_TMRCTR_2_BASEADDR 0x41C20000
#define XPAR_TMRCTR_2_HIGHADDR 0x41C2FFFF
#define XPAR_TMRCTR_2_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_2_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3 */
#define XPAR_TMRCTR_3_DEVICE_ID 0
#define XPAR_TMRCTR_3_BASEADDR 0x41C30000
#define XPAR_TMRCTR_3_HIGHADDR 0x41C3FFFF
#define XPAR_TMRCTR_3_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_3_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4 */
#define XPAR_TMRCTR_4_DEVICE_ID 0
#define XPAR_TMRCTR_4_BASEADDR 0x41C40000
#define XPAR_TMRCTR_4_HIGHADDR 0x41C4FFFF
#define XPAR_TMRCTR_4_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_4_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5 */
#define XPAR_TMRCTR_5_DEVICE_ID 0
#define XPAR_TMRCTR_5_BASEADDR 0x41C50000
#define XPAR_TMRCTR_5_HIGHADDR 0x41C5FFFF
#define XPAR_TMRCTR_5_CLOCK_FREQ_HZ XPAR_IOP3_MB3_TIMERS_SUBSYSTEM_MB3_TIMER_5_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral IOP3_MB3_UARTLITE_D1_D0 */
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_BASEADDR 0x40600000
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_HIGHADDR 0x4060FFFF
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_DEVICE_ID 0
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_BAUDRATE 9600
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_USE_PARITY 0
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_ODD_PARITY 0
#define XPAR_IOP3_MB3_UARTLITE_D1_D0_DATA_BITS 8


/******************************************************************/

/* Canonical definitions for peripheral IOP3_MB3_UARTLITE_D1_D0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_IOP3_MB3_UARTLITE_D1_D0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8


/******************************************************************/

#endif  /* end of protection macro */
