// Copyright (C) 2021 Xilinx, Inc
// SPDX-License-Identifier: BSD-3-Clause

#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral PSU_CORTEXA53_0 */
#define XPAR_PSU_CORTEXA53_0_CPU_CLK_FREQ_HZ 1199988037
#define XPAR_PSU_CORTEXA53_0_TIMESTAMP_CLK_FREQ 99999001


/******************************************************************/

/* Canonical definitions for peripheral PSU_CORTEXA53_0 */
#define XPAR_CPU_CORTEXA53_0_CPU_CLK_FREQ_HZ 1199988037
#define XPAR_CPU_CORTEXA53_0_TIMESTAMP_CLK_FREQ 99999001


/******************************************************************/

 /* Definition for PSS REF CLK FREQUENCY */
#define XPAR_PSU_PSS_REF_CLK_FREQ_HZ 33333000U

#include "xparameters_ps.h"

#define XPS_BOARD_ZCU111


/* Number of Fabric Resets */
#define XPAR_NUM_FABRIC_RESETS 1

#define STDIN_BASEADDRESS 0xFF000000
#define STDOUT_BASEADDRESS 0xFF000000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQMP
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver AVBUF */
#define XPAR_XAVBUF_NUM_INSTANCES 1

/* Definitions for peripheral PSU_DP */
#define XPAR_PSU_DP_DEVICE_ID 0
#define XPAR_PSU_DP_BASEADDR 0xFD4A0000
#define XPAR_PSU_DP_HIGHADDR 0xFD4AFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSU_DP */
#define XPAR_XAVBUF_0_DEVICE_ID XPAR_PSU_DP_DEVICE_ID
#define XPAR_XAVBUF_0_BASEADDR 0xFD4A0000
#define XPAR_XAVBUF_0_HIGHADDR 0xFD4AFFFF


/******************************************************************/

/* Definitions for driver AXIDMA */
#define XPAR_XAXIDMA_NUM_INSTANCES 2

/* Definitions for peripheral AXI_DMA_0 */
#define XPAR_AXI_DMA_0_DEVICE_ID 0
#define XPAR_AXI_DMA_0_BASEADDR 0xA0040000
#define XPAR_AXI_DMA_0_HIGHADDR 0xA0040FFF
#define XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE 0
#define XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE 0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S 1
#define XPAR_AXI_DMA_0_INCLUDE_S2MM 0
#define XPAR_AXI_DMA_0_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_AXI_DMA_0_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXI_DMA_0_INCLUDE_SG 0
#define XPAR_AXI_DMA_0_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS 1
#define XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS 1
#define XPAR_AXI_DMA_0_MM2S_BURST_SIZE 16
#define XPAR_AXI_DMA_0_S2MM_BURST_SIZE 16
#define XPAR_AXI_DMA_0_MICRO_DMA 0
#define XPAR_AXI_DMA_0_ADDR_WIDTH 32
#define XPAR_AXI_DMA_0_SG_LENGTH_WIDTH 14


/* Definitions for peripheral AXI_DMA_1 */
#define XPAR_AXI_DMA_1_DEVICE_ID 1
#define XPAR_AXI_DMA_1_BASEADDR 0xA0041000
#define XPAR_AXI_DMA_1_HIGHADDR 0xA0041FFF
#define XPAR_AXI_DMA_1_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXI_DMA_1_INCLUDE_MM2S_DRE 0
#define XPAR_AXI_DMA_1_INCLUDE_S2MM_DRE 0
#define XPAR_AXI_DMA_1_INCLUDE_MM2S 0
#define XPAR_AXI_DMA_1_INCLUDE_S2MM 1
#define XPAR_AXI_DMA_1_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_AXI_DMA_1_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXI_DMA_1_INCLUDE_SG 0
#define XPAR_AXI_DMA_1_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXI_DMA_1_NUM_MM2S_CHANNELS 1
#define XPAR_AXI_DMA_1_NUM_S2MM_CHANNELS 1
#define XPAR_AXI_DMA_1_MM2S_BURST_SIZE 16
#define XPAR_AXI_DMA_1_S2MM_BURST_SIZE 16
#define XPAR_AXI_DMA_1_MICRO_DMA 0
#define XPAR_AXI_DMA_1_ADDR_WIDTH 32
#define XPAR_AXI_DMA_1_SG_LENGTH_WIDTH 14


/******************************************************************/

/* Canonical definitions for peripheral AXI_DMA_0 */
#define XPAR_AXIDMA_0_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID
#define XPAR_AXIDMA_0_BASEADDR 0xA0040000
#define XPAR_AXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXIDMA_0_INCLUDE_MM2S 1
#define XPAR_AXIDMA_0_INCLUDE_MM2S_DRE 0
#define XPAR_AXIDMA_0_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_AXIDMA_0_INCLUDE_S2MM 0
#define XPAR_AXIDMA_0_INCLUDE_S2MM_DRE 0
#define XPAR_AXIDMA_0_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXIDMA_0_INCLUDE_SG 0
#define XPAR_AXIDMA_0_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXIDMA_0_NUM_MM2S_CHANNELS 1
#define XPAR_AXIDMA_0_NUM_S2MM_CHANNELS 1
#define XPAR_AXIDMA_0_MM2S_BURST_SIZE 16
#define XPAR_AXIDMA_0_S2MM_BURST_SIZE 16
#define XPAR_AXIDMA_0_MICRO_DMA 0
#define XPAR_AXIDMA_0_c_addr_width 32
#define XPAR_AXIDMA_0_c_sg_length_width 14

/* Canonical definitions for peripheral AXI_DMA_1 */
#define XPAR_AXIDMA_1_DEVICE_ID XPAR_AXI_DMA_1_DEVICE_ID
#define XPAR_AXIDMA_1_BASEADDR 0xA0041000
#define XPAR_AXIDMA_1_SG_INCLUDE_STSCNTRL_STRM 0
#define XPAR_AXIDMA_1_INCLUDE_MM2S 0
#define XPAR_AXIDMA_1_INCLUDE_MM2S_DRE 0
#define XPAR_AXIDMA_1_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_AXIDMA_1_INCLUDE_S2MM 1
#define XPAR_AXIDMA_1_INCLUDE_S2MM_DRE 0
#define XPAR_AXIDMA_1_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXIDMA_1_INCLUDE_SG 0
#define XPAR_AXIDMA_1_ENABLE_MULTI_CHANNEL 0
#define XPAR_AXIDMA_1_NUM_MM2S_CHANNELS 1
#define XPAR_AXIDMA_1_NUM_S2MM_CHANNELS 1
#define XPAR_AXIDMA_1_MM2S_BURST_SIZE 16
#define XPAR_AXIDMA_1_S2MM_BURST_SIZE 16
#define XPAR_AXIDMA_1_MICRO_DMA 0
#define XPAR_AXIDMA_1_c_addr_width 32
#define XPAR_AXIDMA_1_c_sg_length_width 14


/******************************************************************/

/* Definitions for driver AXIPMON */
#define XPAR_XAXIPMON_NUM_INSTANCES 4U

/* Definitions for peripheral PSU_APM_0 */
#define XPAR_PSU_APM_0_DEVICE_ID 0U
#define XPAR_PSU_APM_0_BASEADDR 0xFD0B0000U
#define XPAR_PSU_APM_0_HIGHADDR 0xFD0BFFFFU
#define XPAR_PSU_APM_0_GLOBAL_COUNT_WIDTH 32U
#define XPAR_PSU_APM_0_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_PSU_APM_0_ENABLE_EVENT_COUNT 1U
#define XPAR_PSU_APM_0_NUM_MONITOR_SLOTS 6U
#define XPAR_PSU_APM_0_NUM_OF_COUNTERS 10U
#define XPAR_PSU_APM_0_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_PSU_APM_0_ENABLE_EVENT_LOG 0U
#define XPAR_PSU_APM_0_FIFO_AXIS_DEPTH 32U
#define XPAR_PSU_APM_0_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_PSU_APM_0_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_PSU_APM_0_METRIC_COUNT_SCALE 1U
#define XPAR_PSU_APM_0_ENABLE_ADVANCED 1U
#define XPAR_PSU_APM_0_ENABLE_PROFILE 0U
#define XPAR_PSU_APM_0_ENABLE_TRACE 0U
#define XPAR_PSU_APM_0_S_AXI4_BASEADDR 0x00000000U
#define XPAR_PSU_APM_0_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_PSU_APM_0_ENABLE_32BIT_FILTER_ID 1U


/* Definitions for peripheral PSU_APM_1 */
#define XPAR_PSU_APM_1_DEVICE_ID 1U
#define XPAR_PSU_APM_1_BASEADDR 0xFFA00000U
#define XPAR_PSU_APM_1_HIGHADDR 0xFFA0FFFFU
#define XPAR_PSU_APM_1_GLOBAL_COUNT_WIDTH 32U
#define XPAR_PSU_APM_1_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_PSU_APM_1_ENABLE_EVENT_COUNT 1U
#define XPAR_PSU_APM_1_NUM_MONITOR_SLOTS 1U
#define XPAR_PSU_APM_1_NUM_OF_COUNTERS 3U
#define XPAR_PSU_APM_1_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_PSU_APM_1_ENABLE_EVENT_LOG 0U
#define XPAR_PSU_APM_1_FIFO_AXIS_DEPTH 32U
#define XPAR_PSU_APM_1_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_PSU_APM_1_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_PSU_APM_1_METRIC_COUNT_SCALE 1U
#define XPAR_PSU_APM_1_ENABLE_ADVANCED 1U
#define XPAR_PSU_APM_1_ENABLE_PROFILE 0U
#define XPAR_PSU_APM_1_ENABLE_TRACE 0U
#define XPAR_PSU_APM_1_S_AXI4_BASEADDR 0x00000000U
#define XPAR_PSU_APM_1_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_PSU_APM_1_ENABLE_32BIT_FILTER_ID 1U


/* Definitions for peripheral PSU_APM_2 */
#define XPAR_PSU_APM_2_DEVICE_ID 2U
#define XPAR_PSU_APM_2_BASEADDR 0xFFA10000U
#define XPAR_PSU_APM_2_HIGHADDR 0xFFA1FFFFU
#define XPAR_PSU_APM_2_GLOBAL_COUNT_WIDTH 32U
#define XPAR_PSU_APM_2_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_PSU_APM_2_ENABLE_EVENT_COUNT 1U
#define XPAR_PSU_APM_2_NUM_MONITOR_SLOTS 1U
#define XPAR_PSU_APM_2_NUM_OF_COUNTERS 3U
#define XPAR_PSU_APM_2_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_PSU_APM_2_ENABLE_EVENT_LOG 0U
#define XPAR_PSU_APM_2_FIFO_AXIS_DEPTH 32U
#define XPAR_PSU_APM_2_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_PSU_APM_2_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_PSU_APM_2_METRIC_COUNT_SCALE 1U
#define XPAR_PSU_APM_2_ENABLE_ADVANCED 1U
#define XPAR_PSU_APM_2_ENABLE_PROFILE 0U
#define XPAR_PSU_APM_2_ENABLE_TRACE 0U
#define XPAR_PSU_APM_2_S_AXI4_BASEADDR 0x00000000U
#define XPAR_PSU_APM_2_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_PSU_APM_2_ENABLE_32BIT_FILTER_ID 1U


/* Definitions for peripheral PSU_APM_5 */
#define XPAR_PSU_APM_5_DEVICE_ID 3U
#define XPAR_PSU_APM_5_BASEADDR 0xFD490000U
#define XPAR_PSU_APM_5_HIGHADDR 0xFD49FFFFU
#define XPAR_PSU_APM_5_GLOBAL_COUNT_WIDTH 32U
#define XPAR_PSU_APM_5_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_PSU_APM_5_ENABLE_EVENT_COUNT 1U
#define XPAR_PSU_APM_5_NUM_MONITOR_SLOTS 1U
#define XPAR_PSU_APM_5_NUM_OF_COUNTERS 3U
#define XPAR_PSU_APM_5_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_PSU_APM_5_ENABLE_EVENT_LOG 0U
#define XPAR_PSU_APM_5_FIFO_AXIS_DEPTH 32U
#define XPAR_PSU_APM_5_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_PSU_APM_5_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_PSU_APM_5_METRIC_COUNT_SCALE 1U
#define XPAR_PSU_APM_5_ENABLE_ADVANCED 1U
#define XPAR_PSU_APM_5_ENABLE_PROFILE 0U
#define XPAR_PSU_APM_5_ENABLE_TRACE 0U
#define XPAR_PSU_APM_5_S_AXI4_BASEADDR 0x00000000U
#define XPAR_PSU_APM_5_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_PSU_APM_5_ENABLE_32BIT_FILTER_ID 1U


/******************************************************************/

/* Canonical definitions for peripheral PSU_APM_0 */
#define XPAR_AXIPMON_0_DEVICE_ID XPAR_PSU_APM_0_DEVICE_ID
#define XPAR_AXIPMON_0_BASEADDR 0xFD0B0000U
#define XPAR_AXIPMON_0_HIGHADDR 0xFD0BFFFFU
#define XPAR_AXIPMON_0_GLOBAL_COUNT_WIDTH 32U
#define XPAR_AXIPMON_0_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_AXIPMON_0_ENABLE_EVENT_COUNT 1U
#define XPAR_AXIPMON_0_NUM_MONITOR_SLOTS 6U
#define XPAR_AXIPMON_0_NUM_OF_COUNTERS 10U
#define XPAR_AXIPMON_0_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_AXIPMON_0_ENABLE_EVENT_LOG 0U
#define XPAR_AXIPMON_0_FIFO_AXIS_DEPTH 32U
#define XPAR_AXIPMON_0_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_AXIPMON_0_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_AXIPMON_0_METRIC_COUNT_SCALE 1U
#define XPAR_AXIPMON_0_ENABLE_ADVANCED 1U
#define XPAR_AXIPMON_0_ENABLE_PROFILE 0U
#define XPAR_AXIPMON_0_ENABLE_TRACE 0U
#define XPAR_AXIPMON_0_S_AXI4_BASEADDR 0x00000000U
#define XPAR_AXIPMON_0_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_AXIPMON_0_ENABLE_32BIT_FILTER_ID 1U

/* Canonical definitions for peripheral PSU_APM_1 */
#define XPAR_AXIPMON_1_DEVICE_ID XPAR_PSU_APM_1_DEVICE_ID
#define XPAR_AXIPMON_1_BASEADDR 0xFFA00000U
#define XPAR_AXIPMON_1_HIGHADDR 0xFFA0FFFFU
#define XPAR_AXIPMON_1_GLOBAL_COUNT_WIDTH 32U
#define XPAR_AXIPMON_1_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_AXIPMON_1_ENABLE_EVENT_COUNT 1U
#define XPAR_AXIPMON_1_NUM_MONITOR_SLOTS 1U
#define XPAR_AXIPMON_1_NUM_OF_COUNTERS 3U
#define XPAR_AXIPMON_1_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_AXIPMON_1_ENABLE_EVENT_LOG 0U
#define XPAR_AXIPMON_1_FIFO_AXIS_DEPTH 32U
#define XPAR_AXIPMON_1_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_AXIPMON_1_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_AXIPMON_1_METRIC_COUNT_SCALE 1U
#define XPAR_AXIPMON_1_ENABLE_ADVANCED 1U
#define XPAR_AXIPMON_1_ENABLE_PROFILE 0U
#define XPAR_AXIPMON_1_ENABLE_TRACE 0U
#define XPAR_AXIPMON_1_S_AXI4_BASEADDR 0x00000000U
#define XPAR_AXIPMON_1_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_AXIPMON_1_ENABLE_32BIT_FILTER_ID 1U

/* Canonical definitions for peripheral PSU_APM_2 */
#define XPAR_AXIPMON_2_DEVICE_ID XPAR_PSU_APM_2_DEVICE_ID
#define XPAR_AXIPMON_2_BASEADDR 0xFFA10000U
#define XPAR_AXIPMON_2_HIGHADDR 0xFFA1FFFFU
#define XPAR_AXIPMON_2_GLOBAL_COUNT_WIDTH 32U
#define XPAR_AXIPMON_2_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_AXIPMON_2_ENABLE_EVENT_COUNT 1U
#define XPAR_AXIPMON_2_NUM_MONITOR_SLOTS 1U
#define XPAR_AXIPMON_2_NUM_OF_COUNTERS 3U
#define XPAR_AXIPMON_2_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_AXIPMON_2_ENABLE_EVENT_LOG 0U
#define XPAR_AXIPMON_2_FIFO_AXIS_DEPTH 32U
#define XPAR_AXIPMON_2_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_AXIPMON_2_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_AXIPMON_2_METRIC_COUNT_SCALE 1U
#define XPAR_AXIPMON_2_ENABLE_ADVANCED 1U
#define XPAR_AXIPMON_2_ENABLE_PROFILE 0U
#define XPAR_AXIPMON_2_ENABLE_TRACE 0U
#define XPAR_AXIPMON_2_S_AXI4_BASEADDR 0x00000000U
#define XPAR_AXIPMON_2_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_AXIPMON_2_ENABLE_32BIT_FILTER_ID 1U

/* Canonical definitions for peripheral PSU_APM_5 */
#define XPAR_AXIPMON_3_DEVICE_ID XPAR_PSU_APM_5_DEVICE_ID
#define XPAR_AXIPMON_3_BASEADDR 0xFD490000U
#define XPAR_AXIPMON_3_HIGHADDR 0xFD49FFFFU
#define XPAR_AXIPMON_3_GLOBAL_COUNT_WIDTH 32U
#define XPAR_AXIPMON_3_METRICS_SAMPLE_COUNT_WIDTH 32U
#define XPAR_AXIPMON_3_ENABLE_EVENT_COUNT 1U
#define XPAR_AXIPMON_3_NUM_MONITOR_SLOTS 1U
#define XPAR_AXIPMON_3_NUM_OF_COUNTERS 3U
#define XPAR_AXIPMON_3_HAVE_SAMPLED_METRIC_CNT 1U
#define XPAR_AXIPMON_3_ENABLE_EVENT_LOG 0U
#define XPAR_AXIPMON_3_FIFO_AXIS_DEPTH 32U
#define XPAR_AXIPMON_3_FIFO_AXIS_TDATA_WIDTH 56U
#define XPAR_AXIPMON_3_FIFO_AXIS_TID_WIDTH 1U
#define XPAR_AXIPMON_3_METRIC_COUNT_SCALE 1U
#define XPAR_AXIPMON_3_ENABLE_ADVANCED 1U
#define XPAR_AXIPMON_3_ENABLE_PROFILE 0U
#define XPAR_AXIPMON_3_ENABLE_TRACE 0U
#define XPAR_AXIPMON_3_S_AXI4_BASEADDR 0x00000000U
#define XPAR_AXIPMON_3_S_AXI4_HIGHADDR 0x00000000U
#define XPAR_AXIPMON_3_ENABLE_32BIT_FILTER_ID 1U


/******************************************************************/

/* Definitions for driver CSUDMA */
#define XPAR_XCSUDMA_NUM_INSTANCES 1

/* Definitions for peripheral PSU_CSUDMA */
#define XPAR_PSU_CSUDMA_DEVICE_ID 0
#define XPAR_PSU_CSUDMA_BASEADDR 0xFFC80000
#define XPAR_PSU_CSUDMA_HIGHADDR 0xFFC9FFFF
#define XPAR_PSU_CSUDMA_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/

/* Canonical definitions for peripheral PSU_CSUDMA */
#define XPAR_XCSUDMA_0_DEVICE_ID XPAR_PSU_CSUDMA_DEVICE_ID
#define XPAR_XCSUDMA_0_BASEADDR 0xFFC80000
#define XPAR_XCSUDMA_0_HIGHADDR 0xFFC9FFFF
#define XPAR_XCSUDMA_0_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/

/* Definitions for driver DDRCPSU */
#define XPAR_XDDRCPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSU_DDRC_0 */
#define XPAR_PSU_DDRC_0_DEVICE_ID 0
#define XPAR_PSU_DDRC_0_BASEADDR 0xFD070000
#define XPAR_PSU_DDRC_0_HIGHADDR 0xFD070FFF
#define XPAR_PSU_DDRC_0_HAS_ECC 0
#define XPAR_PSU_DDRC_0_DDRC_CLK_FREQ_HZ 533328002


/******************************************************************/

#define XPAR_PSU_DDRC_0_DDR4_ADDR_MAPPING 0
#define XPAR_PSU_DDRC_0_DDR_FREQ_MHZ 1066.656006
#define XPAR_PSU_DDRC_0_VIDEO_BUFFER_SIZE 0
#define XPAR_PSU_DDRC_0_BRC_MAPPING 0
/* Canonical definitions for peripheral PSU_DDRC_0 */
#define XPAR_DDRCPSU_0_DEVICE_ID XPAR_PSU_DDRC_0_DEVICE_ID
#define XPAR_DDRCPSU_0_BASEADDR 0xFD070000
#define XPAR_DDRCPSU_0_HIGHADDR 0xFD070FFF
#define XPAR_DDRCPSU_0_DDRC_CLK_FREQ_HZ 533328002


/******************************************************************/

#define XPAR_DDRCPSU_0_DDR4_ADDR_MAPPING 0
#define XPAR_DDRCPSU_0_DDR_FREQ_MHZ 1066.656006
#define XPAR_DDRCPSU_0_VIDEO_BUFFER_SIZE 0
#define XPAR_DDRCPSU_0_BRC_MAPPING 0
/* Definitions for driver DPDMA */
#define XPAR_XDPDMA_NUM_INSTANCES 1

/* Definitions for peripheral PSU_DPDMA */
#define XPAR_PSU_DPDMA_DEVICE_ID 0
#define XPAR_PSU_DPDMA_BASEADDR 0xFD4C0000
#define XPAR_PSU_DPDMA_HIGHADDR 0xFD4CFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSU_DPDMA */
#define XPAR_XDPDMA_0_DEVICE_ID XPAR_PSU_DPDMA_DEVICE_ID
#define XPAR_XDPDMA_0_BASEADDR 0xFD4C0000
#define XPAR_XDPDMA_0_HIGHADDR 0xFD4CFFFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PSU_ETHERNET_3 */
#define XPAR_PSU_ETHERNET_3_DEVICE_ID 0
#define XPAR_PSU_ETHERNET_3_BASEADDR 0xFF0E0000
#define XPAR_PSU_ETHERNET_3_HIGHADDR 0xFF0EFFFF
#define XPAR_PSU_ETHERNET_3_ENET_CLK_FREQ_HZ 124998749
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_1000MBPS_DIV0 12
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_100MBPS_DIV0 60
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_100MBPS_DIV1 1
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_10MBPS_DIV0 60
#define XPAR_PSU_ETHERNET_3_ENET_SLCR_10MBPS_DIV1 10
#define XPAR_PSU_ETHERNET_3_ENET_TSU_CLK_FREQ_HZ 249997498


/******************************************************************/

#define XPAR_PSU_ETHERNET_3_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSU_ETHERNET_3 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PSU_ETHERNET_3_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xFF0E0000
#define XPAR_XEMACPS_0_HIGHADDR 0xFF0EFFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 124998749
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 12
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 60
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 60
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 10
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 249997498


/******************************************************************/


/* Definitions for peripheral PSU_AFI_0 */
#define XPAR_PSU_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_PSU_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Definitions for peripheral PSU_AFI_1 */
#define XPAR_PSU_AFI_1_S_AXI_BASEADDR 0xFD370000
#define XPAR_PSU_AFI_1_S_AXI_HIGHADDR 0xFD37FFFF


/* Definitions for peripheral PSU_AFI_2 */
#define XPAR_PSU_AFI_2_S_AXI_BASEADDR 0xFD380000
#define XPAR_PSU_AFI_2_S_AXI_HIGHADDR 0xFD38FFFF


/* Definitions for peripheral PSU_AFI_3 */
#define XPAR_PSU_AFI_3_S_AXI_BASEADDR 0xFD390000
#define XPAR_PSU_AFI_3_S_AXI_HIGHADDR 0xFD39FFFF


/* Definitions for peripheral PSU_AFI_4 */
#define XPAR_PSU_AFI_4_S_AXI_BASEADDR 0xFD3A0000
#define XPAR_PSU_AFI_4_S_AXI_HIGHADDR 0xFD3AFFFF


/* Definitions for peripheral PSU_AFI_5 */
#define XPAR_PSU_AFI_5_S_AXI_BASEADDR 0xFD3B0000
#define XPAR_PSU_AFI_5_S_AXI_HIGHADDR 0xFD3BFFFF


/* Definitions for peripheral PSU_AFI_6 */
#define XPAR_PSU_AFI_6_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_PSU_AFI_6_S_AXI_HIGHADDR 0xFF9BFFFF


/* Definitions for peripheral PSU_APU */
#define XPAR_PSU_APU_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_PSU_APU_S_AXI_HIGHADDR 0xFD5CFFFF


/* Definitions for peripheral PSU_CCI_GPV */
#define XPAR_PSU_CCI_GPV_S_AXI_BASEADDR 0xFD6E0000
#define XPAR_PSU_CCI_GPV_S_AXI_HIGHADDR 0xFD6EFFFF


/* Definitions for peripheral PSU_CCI_REG */
#define XPAR_PSU_CCI_REG_S_AXI_BASEADDR 0xFD5E0000
#define XPAR_PSU_CCI_REG_S_AXI_HIGHADDR 0xFD5EFFFF


/* Definitions for peripheral PSU_CRL_APB */
#define XPAR_PSU_CRL_APB_S_AXI_BASEADDR 0xFF5E0000
#define XPAR_PSU_CRL_APB_S_AXI_HIGHADDR 0xFF85FFFF


/* Definitions for peripheral PSU_CTRL_IPI */
#define XPAR_PSU_CTRL_IPI_S_AXI_BASEADDR 0xFF380000
#define XPAR_PSU_CTRL_IPI_S_AXI_HIGHADDR 0xFF3FFFFF


/* Definitions for peripheral PSU_DDR_0 */
#define XPAR_PSU_DDR_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PSU_DDR_0_S_AXI_HIGHADDR 0x7FFFFFFF


/* Definitions for peripheral PSU_DDR_1 */
#define XPAR_PSU_DDR_1_S_AXI_BASEADDR 0x800000000
#define XPAR_PSU_DDR_1_S_AXI_HIGHADDR 0x87FFFFFFF


/* Definitions for peripheral PSU_DDR_PHY */
#define XPAR_PSU_DDR_PHY_S_AXI_BASEADDR 0xFD080000
#define XPAR_PSU_DDR_PHY_S_AXI_HIGHADDR 0xFD08FFFF


/* Definitions for peripheral PSU_DDR_QOS_CTRL */
#define XPAR_PSU_DDR_QOS_CTRL_S_AXI_BASEADDR 0xFD090000
#define XPAR_PSU_DDR_QOS_CTRL_S_AXI_HIGHADDR 0xFD09FFFF


/* Definitions for peripheral PSU_DDR_XMPU0_CFG */
#define XPAR_PSU_DDR_XMPU0_CFG_S_AXI_BASEADDR 0xFD000000
#define XPAR_PSU_DDR_XMPU0_CFG_S_AXI_HIGHADDR 0xFD00FFFF


/* Definitions for peripheral PSU_DDR_XMPU1_CFG */
#define XPAR_PSU_DDR_XMPU1_CFG_S_AXI_BASEADDR 0xFD010000
#define XPAR_PSU_DDR_XMPU1_CFG_S_AXI_HIGHADDR 0xFD01FFFF


/* Definitions for peripheral PSU_DDR_XMPU2_CFG */
#define XPAR_PSU_DDR_XMPU2_CFG_S_AXI_BASEADDR 0xFD020000
#define XPAR_PSU_DDR_XMPU2_CFG_S_AXI_HIGHADDR 0xFD02FFFF


/* Definitions for peripheral PSU_DDR_XMPU3_CFG */
#define XPAR_PSU_DDR_XMPU3_CFG_S_AXI_BASEADDR 0xFD030000
#define XPAR_PSU_DDR_XMPU3_CFG_S_AXI_HIGHADDR 0xFD03FFFF


/* Definitions for peripheral PSU_DDR_XMPU4_CFG */
#define XPAR_PSU_DDR_XMPU4_CFG_S_AXI_BASEADDR 0xFD040000
#define XPAR_PSU_DDR_XMPU4_CFG_S_AXI_HIGHADDR 0xFD04FFFF


/* Definitions for peripheral PSU_DDR_XMPU5_CFG */
#define XPAR_PSU_DDR_XMPU5_CFG_S_AXI_BASEADDR 0xFD050000
#define XPAR_PSU_DDR_XMPU5_CFG_S_AXI_HIGHADDR 0xFD05FFFF


/* Definitions for peripheral PSU_EFUSE */
#define XPAR_PSU_EFUSE_S_AXI_BASEADDR 0xFFCC0000
#define XPAR_PSU_EFUSE_S_AXI_HIGHADDR 0xFFCCFFFF


/* Definitions for peripheral PSU_FPD_GPV */
#define XPAR_PSU_FPD_GPV_S_AXI_BASEADDR 0xFD700000
#define XPAR_PSU_FPD_GPV_S_AXI_HIGHADDR 0xFD7FFFFF


/* Definitions for peripheral PSU_FPD_SLCR */
#define XPAR_PSU_FPD_SLCR_S_AXI_BASEADDR 0xFD610000
#define XPAR_PSU_FPD_SLCR_S_AXI_HIGHADDR 0xFD68FFFF


/* Definitions for peripheral PSU_FPD_SLCR_SECURE */
#define XPAR_PSU_FPD_SLCR_SECURE_S_AXI_BASEADDR 0xFD690000
#define XPAR_PSU_FPD_SLCR_SECURE_S_AXI_HIGHADDR 0xFD6CFFFF


/* Definitions for peripheral PSU_FPD_XMPU_CFG */
#define XPAR_PSU_FPD_XMPU_CFG_S_AXI_BASEADDR 0xFD5D0000
#define XPAR_PSU_FPD_XMPU_CFG_S_AXI_HIGHADDR 0xFD5DFFFF


/* Definitions for peripheral PSU_FPD_XMPU_SINK */
#define XPAR_PSU_FPD_XMPU_SINK_S_AXI_BASEADDR 0xFD4F0000
#define XPAR_PSU_FPD_XMPU_SINK_S_AXI_HIGHADDR 0xFD4FFFFF


/* Definitions for peripheral PSU_GPU */
#define XPAR_PSU_GPU_S_AXI_BASEADDR 0xFD4B0000
#define XPAR_PSU_GPU_S_AXI_HIGHADDR 0xFD4BFFFF


/* Definitions for peripheral PSU_IOU_SCNTR */
#define XPAR_PSU_IOU_SCNTR_S_AXI_BASEADDR 0xFF250000
#define XPAR_PSU_IOU_SCNTR_S_AXI_HIGHADDR 0xFF25FFFF


/* Definitions for peripheral PSU_IOU_SCNTRS */
#define XPAR_PSU_IOU_SCNTRS_S_AXI_BASEADDR 0xFF260000
#define XPAR_PSU_IOU_SCNTRS_S_AXI_HIGHADDR 0xFF26FFFF


/* Definitions for peripheral PSU_IOUSECURE_SLCR */
#define XPAR_PSU_IOUSECURE_SLCR_S_AXI_BASEADDR 0xFF240000
#define XPAR_PSU_IOUSECURE_SLCR_S_AXI_HIGHADDR 0xFF24FFFF


/* Definitions for peripheral PSU_IOUSLCR_0 */
#define XPAR_PSU_IOUSLCR_0_S_AXI_BASEADDR 0xFF180000
#define XPAR_PSU_IOUSLCR_0_S_AXI_HIGHADDR 0xFF23FFFF


/* Definitions for peripheral PSU_LPD_SLCR */
#define XPAR_PSU_LPD_SLCR_S_AXI_BASEADDR 0xFF410000
#define XPAR_PSU_LPD_SLCR_S_AXI_HIGHADDR 0xFF4AFFFF


/* Definitions for peripheral PSU_LPD_SLCR_SECURE */
#define XPAR_PSU_LPD_SLCR_SECURE_S_AXI_BASEADDR 0xFF4B0000
#define XPAR_PSU_LPD_SLCR_SECURE_S_AXI_HIGHADDR 0xFF4DFFFF


/* Definitions for peripheral PSU_LPD_XPPU */
#define XPAR_PSU_LPD_XPPU_S_AXI_BASEADDR 0xFF980000
#define XPAR_PSU_LPD_XPPU_S_AXI_HIGHADDR 0xFF99FFFF


/* Definitions for peripheral PSU_LPD_XPPU_SINK */
#define XPAR_PSU_LPD_XPPU_SINK_S_AXI_BASEADDR 0xFF9C0000
#define XPAR_PSU_LPD_XPPU_SINK_S_AXI_HIGHADDR 0xFF9CFFFF


/* Definitions for peripheral PSU_MBISTJTAG */
#define XPAR_PSU_MBISTJTAG_S_AXI_BASEADDR 0xFFCF0000
#define XPAR_PSU_MBISTJTAG_S_AXI_HIGHADDR 0xFFCFFFFF


/* Definitions for peripheral PSU_MESSAGE_BUFFERS */
#define XPAR_PSU_MESSAGE_BUFFERS_S_AXI_BASEADDR 0xFF990000
#define XPAR_PSU_MESSAGE_BUFFERS_S_AXI_HIGHADDR 0xFF99FFFF


/* Definitions for peripheral PSU_OCM */
#define XPAR_PSU_OCM_S_AXI_BASEADDR 0xFF960000
#define XPAR_PSU_OCM_S_AXI_HIGHADDR 0xFF96FFFF


/* Definitions for peripheral PSU_OCM_RAM_0 */
#define XPAR_PSU_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PSU_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PSU_OCM_XMPU_CFG */
#define XPAR_PSU_OCM_XMPU_CFG_S_AXI_BASEADDR 0xFFA70000
#define XPAR_PSU_OCM_XMPU_CFG_S_AXI_HIGHADDR 0xFFA7FFFF


/* Definitions for peripheral PSU_PMU_GLOBAL_0 */
#define XPAR_PSU_PMU_GLOBAL_0_S_AXI_BASEADDR 0xFFD80000
#define XPAR_PSU_PMU_GLOBAL_0_S_AXI_HIGHADDR 0xFFDBFFFF


/* Definitions for peripheral PSU_QSPI_LINEAR_0 */
#define XPAR_PSU_QSPI_LINEAR_0_S_AXI_BASEADDR 0xC0000000
#define XPAR_PSU_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xDFFFFFFF


/* Definitions for peripheral PSU_R5_0_ATCM_GLOBAL */
#define XPAR_PSU_R5_0_ATCM_GLOBAL_S_AXI_BASEADDR 0xFFE00000
#define XPAR_PSU_R5_0_ATCM_GLOBAL_S_AXI_HIGHADDR 0xFFE0FFFF


/* Definitions for peripheral PSU_R5_0_BTCM_GLOBAL */
#define XPAR_PSU_R5_0_BTCM_GLOBAL_S_AXI_BASEADDR 0xFFE20000
#define XPAR_PSU_R5_0_BTCM_GLOBAL_S_AXI_HIGHADDR 0xFFE2FFFF


/* Definitions for peripheral PSU_R5_1_ATCM_GLOBAL */
#define XPAR_PSU_R5_1_ATCM_GLOBAL_S_AXI_BASEADDR 0xFFE90000
#define XPAR_PSU_R5_1_ATCM_GLOBAL_S_AXI_HIGHADDR 0xFFE9FFFF


/* Definitions for peripheral PSU_R5_1_BTCM_GLOBAL */
#define XPAR_PSU_R5_1_BTCM_GLOBAL_S_AXI_BASEADDR 0xFFEB0000
#define XPAR_PSU_R5_1_BTCM_GLOBAL_S_AXI_HIGHADDR 0xFFEBFFFF


/* Definitions for peripheral PSU_R5_TCM_RAM_GLOBAL */
#define XPAR_PSU_R5_TCM_RAM_GLOBAL_S_AXI_BASEADDR 0xFFE00000
#define XPAR_PSU_R5_TCM_RAM_GLOBAL_S_AXI_HIGHADDR 0xFFE3FFFF


/* Definitions for peripheral PSU_RPU */
#define XPAR_PSU_RPU_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_PSU_RPU_S_AXI_HIGHADDR 0xFF9AFFFF


/* Definitions for peripheral PSU_RSA */
#define XPAR_PSU_RSA_S_AXI_BASEADDR 0xFFCE0000
#define XPAR_PSU_RSA_S_AXI_HIGHADDR 0xFFCEFFFF


/* Definitions for peripheral PSU_SATA */
#define XPAR_PSU_SATA_S_AXI_BASEADDR 0xFD0C0000
#define XPAR_PSU_SATA_S_AXI_HIGHADDR 0xFD0CFFFF


/* Definitions for peripheral PSU_SERDES */
#define XPAR_PSU_SERDES_S_AXI_BASEADDR 0xFD400000
#define XPAR_PSU_SERDES_S_AXI_HIGHADDR 0xFD47FFFF


/* Definitions for peripheral PSU_SIOU */
#define XPAR_PSU_SIOU_S_AXI_BASEADDR 0xFD3D0000
#define XPAR_PSU_SIOU_S_AXI_HIGHADDR 0xFD3DFFFF


/* Definitions for peripheral PSU_SMMU_GPV */
#define XPAR_PSU_SMMU_GPV_S_AXI_BASEADDR 0xFD800000
#define XPAR_PSU_SMMU_GPV_S_AXI_HIGHADDR 0xFDFFFFFF


/* Definitions for peripheral PSU_SMMU_REG */
#define XPAR_PSU_SMMU_REG_S_AXI_BASEADDR 0xFD5F0000
#define XPAR_PSU_SMMU_REG_S_AXI_HIGHADDR 0xFD5FFFFF


/* Definitions for peripheral PSU_USB_0 */
#define XPAR_PSU_USB_0_S_AXI_BASEADDR 0xFF9D0000
#define XPAR_PSU_USB_0_S_AXI_HIGHADDR 0xFF9DFFFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PSU_GPIO_0 */
#define XPAR_PSU_GPIO_0_DEVICE_ID 0
#define XPAR_PSU_GPIO_0_BASEADDR 0xFF0A0000
#define XPAR_PSU_GPIO_0_HIGHADDR 0xFF0AFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSU_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PSU_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xFF0A0000
#define XPAR_XGPIOPS_0_HIGHADDR 0xFF0AFFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 2

/* Definitions for peripheral PSU_I2C_0 */
#define XPAR_PSU_I2C_0_DEVICE_ID 0
#define XPAR_PSU_I2C_0_BASEADDR 0xFF020000
#define XPAR_PSU_I2C_0_HIGHADDR 0xFF02FFFF
#define XPAR_PSU_I2C_0_I2C_CLK_FREQ_HZ 99999001


/* Definitions for peripheral PSU_I2C_1 */
#define XPAR_PSU_I2C_1_DEVICE_ID 1
#define XPAR_PSU_I2C_1_BASEADDR 0xFF030000
#define XPAR_PSU_I2C_1_HIGHADDR 0xFF03FFFF
#define XPAR_PSU_I2C_1_I2C_CLK_FREQ_HZ 99999001


/******************************************************************/

/* Canonical definitions for peripheral PSU_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PSU_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xFF020000
#define XPAR_XIICPS_0_HIGHADDR 0xFF02FFFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 99999001

/* Canonical definitions for peripheral PSU_I2C_1 */
#define XPAR_XIICPS_1_DEVICE_ID XPAR_PSU_I2C_1_DEVICE_ID
#define XPAR_XIICPS_1_BASEADDR 0xFF030000
#define XPAR_XIICPS_1_HIGHADDR 0xFF03FFFF
#define XPAR_XIICPS_1_I2C_CLK_FREQ_HZ 99999001


/******************************************************************/

#define  XPAR_XIPIPSU_NUM_INSTANCES  1U

/* Parameter definitions for peripheral psu_ipi_0 */
#define  XPAR_PSU_IPI_0_DEVICE_ID  0U
#define  XPAR_PSU_IPI_0_BASE_ADDRESS  0xFF300000U
#define  XPAR_PSU_IPI_0_BIT_MASK  0x00000001U
#define  XPAR_PSU_IPI_0_BUFFER_INDEX  2U
#define  XPAR_PSU_IPI_0_INT_ID  67U

/* Canonical definitions for peripheral psu_ipi_0 */
#define  XPAR_XIPIPSU_0_DEVICE_ID	XPAR_PSU_IPI_0_DEVICE_ID
#define  XPAR_XIPIPSU_0_BASE_ADDRESS	XPAR_PSU_IPI_0_BASE_ADDRESS
#define  XPAR_XIPIPSU_0_BIT_MASK	XPAR_PSU_IPI_0_BIT_MASK
#define  XPAR_XIPIPSU_0_BUFFER_INDEX	XPAR_PSU_IPI_0_BUFFER_INDEX
#define  XPAR_XIPIPSU_0_INT_ID	XPAR_PSU_IPI_0_INT_ID

#define  XPAR_XIPIPSU_NUM_TARGETS  7U

#define  XPAR_PSU_IPI_0_BIT_MASK  0x00000001U
#define  XPAR_PSU_IPI_0_BUFFER_INDEX  2U
#define  XPAR_PSU_IPI_1_BIT_MASK  0x00000100U
#define  XPAR_PSU_IPI_1_BUFFER_INDEX  0U
#define  XPAR_PSU_IPI_2_BIT_MASK  0x00000200U
#define  XPAR_PSU_IPI_2_BUFFER_INDEX  1U
#define  XPAR_PSU_IPI_3_BIT_MASK  0x00010000U
#define  XPAR_PSU_IPI_3_BUFFER_INDEX  7U
#define  XPAR_PSU_IPI_4_BIT_MASK  0x00020000U
#define  XPAR_PSU_IPI_4_BUFFER_INDEX  7U
#define  XPAR_PSU_IPI_5_BIT_MASK  0x00040000U
#define  XPAR_PSU_IPI_5_BUFFER_INDEX  7U
#define  XPAR_PSU_IPI_6_BIT_MASK  0x00080000U
#define  XPAR_PSU_IPI_6_BUFFER_INDEX  7U
/* Target List for referring to processor IPI Targets */

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_0_CH0_MASK  XPAR_PSU_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_0_CH0_INDEX  0U

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_1_CH0_MASK  XPAR_PSU_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_1_CH0_INDEX  0U

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_2_CH0_MASK  XPAR_PSU_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_2_CH0_INDEX  0U

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_3_CH0_MASK  XPAR_PSU_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXA53_3_CH0_INDEX  0U

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXR5_0_CH0_MASK  XPAR_PSU_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXR5_0_CH0_INDEX  1U

#define  XPAR_XIPIPS_TARGET_PSU_CORTEXR5_1_CH0_MASK  XPAR_PSU_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_CORTEXR5_1_CH0_INDEX  2U

#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH0_MASK  XPAR_PSU_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH0_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH1_MASK  XPAR_PSU_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH1_INDEX  4U
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH2_MASK  XPAR_PSU_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH2_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH3_MASK  XPAR_PSU_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSU_PMU_0_CH3_INDEX  6U

/* Definitions for driver QSPIPSU */
#define XPAR_XQSPIPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSU_QSPI_0 */
#define XPAR_PSU_QSPI_0_DEVICE_ID 0
#define XPAR_PSU_QSPI_0_BASEADDR 0xFF0F0000
#define XPAR_PSU_QSPI_0_HIGHADDR 0xFF0FFFFF
#define XPAR_PSU_QSPI_0_QSPI_CLK_FREQ_HZ 124998749
#define XPAR_PSU_QSPI_0_QSPI_MODE 2
#define XPAR_PSU_QSPI_0_QSPI_BUS_WIDTH 2


/******************************************************************/

#define XPAR_PSU_QSPI_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSU_QSPI_0 */
#define XPAR_XQSPIPSU_0_DEVICE_ID XPAR_PSU_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPSU_0_BASEADDR 0xFF0F0000
#define XPAR_XQSPIPSU_0_HIGHADDR 0xFF0FFFFF
#define XPAR_XQSPIPSU_0_QSPI_CLK_FREQ_HZ 124998749
#define XPAR_XQSPIPSU_0_QSPI_MODE 2
#define XPAR_XQSPIPSU_0_QSPI_BUS_WIDTH 2
#define XPAR_XQSPIPSU_0_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver RESETPS and CLOCKPS */
#define XPAR_XCRPSU_NUM_INSTANCES 1U

/* Definitions for peripheral PSU_CR_0 */
#define XPAR_PSU_CR_DEVICE_ID 0

/******************************************************************/

/* Definitions for peripheral PSU_CRF_APB */
#define XPAR_PSU_CRF_APB_S_AXI_BASEADDR 0xFD1A0000
#define XPAR_PSU_CRF_APB_S_AXI_HIGHADDR 0xFD2DFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSU_CR_0 */
#define XPAR_XCRPSU_0_DEVICE_ID 0

/******************************************************************/


/* Definitions for peripheral PSU_PMU_IOMODULE */
#define XPAR_PSU_PMU_IOMODULE_S_AXI_BASEADDR 0xFFD40000
#define XPAR_PSU_PMU_IOMODULE_S_AXI_HIGHADDR 0xFFD5FFFF


/* Definitions for peripheral PSU_LPD_SLCR */
#define XPAR_PSU_LPD_SLCR_S_AXI_BASEADDR 0xFF410000
#define XPAR_PSU_LPD_SLCR_S_AXI_HIGHADDR 0xFF4AFFFF


/******************************************************************/

/* Definitions for driver RFDC */
#define XPAR_XRFDC_NUM_INSTANCES 1

/* Definitions for peripheral USP_RF_DATA_CONVERTER_0 */
#define XPAR_USP_RF_DATA_CONVERTER_0_DEVICE_ID 0
#define XPAR_USP_RF_DATA_CONVERTER_0_BASEADDR 0xA0000000
#define XPAR_USP_RF_DATA_CONVERTER_0_HIGHADDR 0xA003FFFF
#define XPAR_USP_RF_DATA_CONVERTER_0_HIGH_SPEED_ADC 1
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_MASTER 228
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_MASTER 228
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_SOURCE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_SYSREF_SOURCE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_ENABLE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_SAMPLING_RATE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_REFCLK_FREQ 1000.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_FABRIC_FREQ 62.500
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC0_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE00_ENABLE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE00 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE01_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE01 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE02_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE02 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE03_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE03 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH00 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE00 8
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO00_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER00_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH01 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO01_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER01_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE01 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH02 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO02_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER02_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE02 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH03 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO03_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE03 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER03_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_SAMPLING_RATE 6.4
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_REFCLK_FREQ 6400.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC1_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE10_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE10 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE11_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE11 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE12_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE12 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE13_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE13 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH10 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO10_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER10_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE10 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH11 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO11_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER11_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE11 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH12 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO12_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER12_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE12 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH13 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO13_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER13_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE13 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_SAMPLING_RATE 6.4
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_REFCLK_FREQ 6400.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC2_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE20_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE20 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE21_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE21 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE22_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE22 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE23_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE23 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH20 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO20_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER20_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE20 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH21 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO21_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER21_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE21 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH22 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO22_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER22_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE22 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH23 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO23_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER23_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE23 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_SAMPLING_RATE 6.4
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_REFCLK_FREQ 6400.000
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC3_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE30_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE30 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE31_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE31 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE32_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE32 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_SLICE33_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INVSINC_CTRL33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_MODE33 2
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DECODER_MODE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH30 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO30_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER30_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE30 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH31 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO31_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER31_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE31 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH32 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO32_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER32_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE32 3
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_TYPE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_DATA_WIDTH33 16
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_INTERPOLATION_MODE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_FIFO33_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_ADDER33_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_DAC_MIXER_TYPE33 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_ENABLE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_SAMPLING_RATE 1.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_REFCLK_FREQ 1000.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_FABRIC_FREQ 62.500
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC0_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE00_ENABLE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE00 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE01_ENABLE 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE01 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE02_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE02 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE03_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE03 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH00 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE00 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO00_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE00 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH01 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE01 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO01_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE01 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH02 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE02 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO02_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE02 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH03 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE03 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO03_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE03 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_SAMPLING_RATE 2.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_REFCLK_FREQ 2000.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC1_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE10_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE10 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE11_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE11 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE12_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE12 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE13_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE13 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH10 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE10 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO10_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE10 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH11 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE11 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO11_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE11 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH12 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE12 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO12_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE12 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH13 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE13 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO13_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE13 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_SAMPLING_RATE 2.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_REFCLK_FREQ 2000.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC2_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE20_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE20 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE21_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE21 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE22_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE22 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE23_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE23 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH20 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE20 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO20_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE20 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH21 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE21 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO21_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE21 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH22 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE22 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO22_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE22 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH23 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE23 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO23_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE23 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_PLL_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_SAMPLING_RATE 2.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_REFCLK_FREQ 2000.000
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_FABRIC_FREQ 0.0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_FBDIV 10
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_OUTDIV 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_REFCLK_DIV 1
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC3_BAND 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE30_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE30 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE31_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE31 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE32_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE32 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_SLICE33_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_MODE33 2
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH30 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE30 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO30_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE30 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH31 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE31 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO31_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE31 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH32 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE32 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO32_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE32 3
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_TYPE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DATA_WIDTH33 8
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_DECIMATION_MODE33 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_FIFO33_ENABLE 0
#define XPAR_USP_RF_DATA_CONVERTER_0_ADC_MIXER_TYPE33 3


/******************************************************************/

/* Canonical definitions for peripheral USP_RF_DATA_CONVERTER_0 */
#define XPAR_XRFDC_0_DEVICE_ID XPAR_USP_RF_DATA_CONVERTER_0_DEVICE_ID
#define XPAR_XRFDC_0_BASEADDR 0xA0000000
#define XPAR_XRFDC_0_HIGHADDR 0xA003FFFF
#define XPAR_XRFDC_0_High_Speed_ADC 1
#define XPAR_XRFDC_0_Sysref_Master 228
#define XPAR_XRFDC_0_Sysref_Master 228
#define XPAR_XRFDC_0_Sysref_Source 1
#define XPAR_XRFDC_0_Sysref_Source 1
#define XPAR_XRFDC_0_DAC0_Enable 1
#define XPAR_XRFDC_0_DAC0_PLL_Enable 0
#define XPAR_XRFDC_0_DAC0_Sampling_Rate 1
#define XPAR_XRFDC_0_DAC0_Refclk_Freq 1000.000
#define XPAR_XRFDC_0_DAC0_Fabric_Freq 62.500
#define XPAR_XRFDC_0_DAC0_FBDIV 10
#define XPAR_XRFDC_0_DAC0_OutDiv 2
#define XPAR_XRFDC_0_DAC0_Refclk_Div 1
#define XPAR_XRFDC_0_DAC0_Band 0
#define XPAR_XRFDC_0_DAC_Slice00_Enable 1
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl00 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode00 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode00 0
#define XPAR_XRFDC_0_DAC_Slice01_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl01 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode01 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode01 0
#define XPAR_XRFDC_0_DAC_Slice02_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl02 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode02 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode02 0
#define XPAR_XRFDC_0_DAC_Slice03_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl03 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode03 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode03 0
#define XPAR_XRFDC_0_DAC_Data_Type00 0
#define XPAR_XRFDC_0_DAC_Data_Width00 2
#define XPAR_XRFDC_0_DAC_Interpolation_Mode00 8
#define XPAR_XRFDC_0_DAC_Fifo00_Enable 0
#define XPAR_XRFDC_0_DAC_Adder00_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type00 0
#define XPAR_XRFDC_0_DAC_Data_Type01 0
#define XPAR_XRFDC_0_DAC_Data_Width01 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode01 0
#define XPAR_XRFDC_0_DAC_Fifo01_Enable 0
#define XPAR_XRFDC_0_DAC_Adder01_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type01 3
#define XPAR_XRFDC_0_DAC_Data_Type02 0
#define XPAR_XRFDC_0_DAC_Data_Width02 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode02 0
#define XPAR_XRFDC_0_DAC_Fifo02_Enable 0
#define XPAR_XRFDC_0_DAC_Adder02_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type02 3
#define XPAR_XRFDC_0_DAC_Data_Type03 0
#define XPAR_XRFDC_0_DAC_Data_Width03 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode03 0
#define XPAR_XRFDC_0_DAC_Fifo03_Enable 0
#define XPAR_XRFDC_0_DAC_Adder03_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type03 3
#define XPAR_XRFDC_0_DAC1_Enable 0
#define XPAR_XRFDC_0_DAC1_PLL_Enable 0
#define XPAR_XRFDC_0_DAC1_Sampling_Rate 6.4
#define XPAR_XRFDC_0_DAC1_Refclk_Freq 6400.000
#define XPAR_XRFDC_0_DAC1_Fabric_Freq 0.0
#define XPAR_XRFDC_0_DAC1_FBDIV 10
#define XPAR_XRFDC_0_DAC1_OutDiv 2
#define XPAR_XRFDC_0_DAC1_Refclk_Div 1
#define XPAR_XRFDC_0_DAC1_Band 0
#define XPAR_XRFDC_0_DAC_Slice10_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl10 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode10 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode10 0
#define XPAR_XRFDC_0_DAC_Slice11_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl11 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode11 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode11 0
#define XPAR_XRFDC_0_DAC_Slice12_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl12 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode12 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode12 0
#define XPAR_XRFDC_0_DAC_Slice13_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl13 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode13 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode13 0
#define XPAR_XRFDC_0_DAC_Data_Type10 0
#define XPAR_XRFDC_0_DAC_Data_Width10 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode10 0
#define XPAR_XRFDC_0_DAC_Fifo10_Enable 0
#define XPAR_XRFDC_0_DAC_Adder10_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type10 3
#define XPAR_XRFDC_0_DAC_Data_Type11 0
#define XPAR_XRFDC_0_DAC_Data_Width11 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode11 0
#define XPAR_XRFDC_0_DAC_Fifo11_Enable 0
#define XPAR_XRFDC_0_DAC_Adder11_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type11 3
#define XPAR_XRFDC_0_DAC_Data_Type12 0
#define XPAR_XRFDC_0_DAC_Data_Width12 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode12 0
#define XPAR_XRFDC_0_DAC_Fifo12_Enable 0
#define XPAR_XRFDC_0_DAC_Adder12_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type12 3
#define XPAR_XRFDC_0_DAC_Data_Type13 0
#define XPAR_XRFDC_0_DAC_Data_Width13 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode13 0
#define XPAR_XRFDC_0_DAC_Fifo13_Enable 0
#define XPAR_XRFDC_0_DAC_Adder13_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type13 3
#define XPAR_XRFDC_0_DAC2_Enable 0
#define XPAR_XRFDC_0_DAC2_PLL_Enable 0
#define XPAR_XRFDC_0_DAC2_Sampling_Rate 6.4
#define XPAR_XRFDC_0_DAC2_Refclk_Freq 6400.000
#define XPAR_XRFDC_0_DAC2_Fabric_Freq 0.0
#define XPAR_XRFDC_0_DAC2_FBDIV 10
#define XPAR_XRFDC_0_DAC2_OutDiv 2
#define XPAR_XRFDC_0_DAC2_Refclk_Div 1
#define XPAR_XRFDC_0_DAC2_Band 0
#define XPAR_XRFDC_0_DAC_Slice20_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl20 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode20 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode20 0
#define XPAR_XRFDC_0_DAC_Slice21_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl21 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode21 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode21 0
#define XPAR_XRFDC_0_DAC_Slice22_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl22 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode22 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode22 0
#define XPAR_XRFDC_0_DAC_Slice23_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl23 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode23 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode23 0
#define XPAR_XRFDC_0_DAC_Data_Type20 0
#define XPAR_XRFDC_0_DAC_Data_Width20 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode20 0
#define XPAR_XRFDC_0_DAC_Fifo20_Enable 0
#define XPAR_XRFDC_0_DAC_Adder20_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type20 3
#define XPAR_XRFDC_0_DAC_Data_Type21 0
#define XPAR_XRFDC_0_DAC_Data_Width21 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode21 0
#define XPAR_XRFDC_0_DAC_Fifo21_Enable 0
#define XPAR_XRFDC_0_DAC_Adder21_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type21 3
#define XPAR_XRFDC_0_DAC_Data_Type22 0
#define XPAR_XRFDC_0_DAC_Data_Width22 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode22 0
#define XPAR_XRFDC_0_DAC_Fifo22_Enable 0
#define XPAR_XRFDC_0_DAC_Adder22_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type22 3
#define XPAR_XRFDC_0_DAC_Data_Type23 0
#define XPAR_XRFDC_0_DAC_Data_Width23 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode23 0
#define XPAR_XRFDC_0_DAC_Fifo23_Enable 0
#define XPAR_XRFDC_0_DAC_Adder23_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type23 3
#define XPAR_XRFDC_0_DAC3_Enable 0
#define XPAR_XRFDC_0_DAC3_PLL_Enable 0
#define XPAR_XRFDC_0_DAC3_Sampling_Rate 6.4
#define XPAR_XRFDC_0_DAC3_Refclk_Freq 6400.000
#define XPAR_XRFDC_0_DAC3_Fabric_Freq 0.0
#define XPAR_XRFDC_0_DAC3_FBDIV 10
#define XPAR_XRFDC_0_DAC3_OutDiv 2
#define XPAR_XRFDC_0_DAC3_Refclk_Div 1
#define XPAR_XRFDC_0_DAC3_Band 0
#define XPAR_XRFDC_0_DAC_Slice30_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl30 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode30 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode30 0
#define XPAR_XRFDC_0_DAC_Slice31_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl31 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode31 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode31 0
#define XPAR_XRFDC_0_DAC_Slice32_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl32 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode32 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode32 0
#define XPAR_XRFDC_0_DAC_Slice33_Enable 0
#define XPAR_XRFDC_0_DAC_Invsinc_Ctrl33 0
#define XPAR_XRFDC_0_DAC_Mixer_Mode33 2
#define XPAR_XRFDC_0_DAC_Decoder_Mode33 0
#define XPAR_XRFDC_0_DAC_Data_Type30 0
#define XPAR_XRFDC_0_DAC_Data_Width30 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode30 0
#define XPAR_XRFDC_0_DAC_Fifo30_Enable 0
#define XPAR_XRFDC_0_DAC_Adder30_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type30 3
#define XPAR_XRFDC_0_DAC_Data_Type31 0
#define XPAR_XRFDC_0_DAC_Data_Width31 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode31 0
#define XPAR_XRFDC_0_DAC_Fifo31_Enable 0
#define XPAR_XRFDC_0_DAC_Adder31_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type31 3
#define XPAR_XRFDC_0_DAC_Data_Type32 0
#define XPAR_XRFDC_0_DAC_Data_Width32 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode32 0
#define XPAR_XRFDC_0_DAC_Fifo32_Enable 0
#define XPAR_XRFDC_0_DAC_Adder32_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type32 3
#define XPAR_XRFDC_0_DAC_Data_Type33 0
#define XPAR_XRFDC_0_DAC_Data_Width33 16
#define XPAR_XRFDC_0_DAC_Interpolation_Mode33 0
#define XPAR_XRFDC_0_DAC_Fifo33_Enable 0
#define XPAR_XRFDC_0_DAC_Adder33_Enable 0
#define XPAR_XRFDC_0_DAC_Mixer_Type33 3
#define XPAR_XRFDC_0_ADC0_Enable 1
#define XPAR_XRFDC_0_ADC0_PLL_Enable 0
#define XPAR_XRFDC_0_ADC0_Sampling_Rate 1.0
#define XPAR_XRFDC_0_ADC0_Refclk_Freq 1000.000
#define XPAR_XRFDC_0_ADC0_Fabric_Freq 62.500
#define XPAR_XRFDC_0_ADC0_FBDIV 10
#define XPAR_XRFDC_0_ADC0_OutDiv 2
#define XPAR_XRFDC_0_ADC0_Refclk_Div 1
#define XPAR_XRFDC_0_ADC0_Band 0
#define XPAR_XRFDC_0_ADC_Slice00_Enable 1
#define XPAR_XRFDC_0_ADC_Mixer_Mode00 2
#define XPAR_XRFDC_0_ADC_Slice01_Enable 1
#define XPAR_XRFDC_0_ADC_Mixer_Mode01 2
#define XPAR_XRFDC_0_ADC_Slice02_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode02 2
#define XPAR_XRFDC_0_ADC_Slice03_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode03 2
#define XPAR_XRFDC_0_ADC_Data_Type00 0
#define XPAR_XRFDC_0_ADC_Data_Width00 2
#define XPAR_XRFDC_0_ADC_Decimation_Mode00 8
#define XPAR_XRFDC_0_ADC_Fifo00_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type00 0
#define XPAR_XRFDC_0_ADC_Data_Type01 0
#define XPAR_XRFDC_0_ADC_Data_Width01 2
#define XPAR_XRFDC_0_ADC_Decimation_Mode01 8
#define XPAR_XRFDC_0_ADC_Fifo01_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type01 0
#define XPAR_XRFDC_0_ADC_Data_Type02 0
#define XPAR_XRFDC_0_ADC_Data_Width02 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode02 0
#define XPAR_XRFDC_0_ADC_Fifo02_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type02 3
#define XPAR_XRFDC_0_ADC_Data_Type03 0
#define XPAR_XRFDC_0_ADC_Data_Width03 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode03 0
#define XPAR_XRFDC_0_ADC_Fifo03_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type03 3
#define XPAR_XRFDC_0_ADC1_Enable 0
#define XPAR_XRFDC_0_ADC1_PLL_Enable 0
#define XPAR_XRFDC_0_ADC1_Sampling_Rate 2.0
#define XPAR_XRFDC_0_ADC1_Refclk_Freq 2000.000
#define XPAR_XRFDC_0_ADC1_Fabric_Freq 0.0
#define XPAR_XRFDC_0_ADC1_FBDIV 10
#define XPAR_XRFDC_0_ADC1_OutDiv 2
#define XPAR_XRFDC_0_ADC1_Refclk_Div 1
#define XPAR_XRFDC_0_ADC1_Band 0
#define XPAR_XRFDC_0_ADC_Slice10_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode10 2
#define XPAR_XRFDC_0_ADC_Slice11_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode11 2
#define XPAR_XRFDC_0_ADC_Slice12_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode12 2
#define XPAR_XRFDC_0_ADC_Slice13_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode13 2
#define XPAR_XRFDC_0_ADC_Data_Type10 0
#define XPAR_XRFDC_0_ADC_Data_Width10 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode10 0
#define XPAR_XRFDC_0_ADC_Fifo10_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type10 3
#define XPAR_XRFDC_0_ADC_Data_Type11 0
#define XPAR_XRFDC_0_ADC_Data_Width11 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode11 0
#define XPAR_XRFDC_0_ADC_Fifo11_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type11 3
#define XPAR_XRFDC_0_ADC_Data_Type12 0
#define XPAR_XRFDC_0_ADC_Data_Width12 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode12 0
#define XPAR_XRFDC_0_ADC_Fifo12_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type12 3
#define XPAR_XRFDC_0_ADC_Data_Type13 0
#define XPAR_XRFDC_0_ADC_Data_Width13 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode13 0
#define XPAR_XRFDC_0_ADC_Fifo13_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type13 3
#define XPAR_XRFDC_0_ADC2_Enable 0
#define XPAR_XRFDC_0_ADC2_PLL_Enable 0
#define XPAR_XRFDC_0_ADC2_Sampling_Rate 2.0
#define XPAR_XRFDC_0_ADC2_Refclk_Freq 2000.000
#define XPAR_XRFDC_0_ADC2_Fabric_Freq 0.0
#define XPAR_XRFDC_0_ADC2_FBDIV 10
#define XPAR_XRFDC_0_ADC2_OutDiv 2
#define XPAR_XRFDC_0_ADC2_Refclk_Div 1
#define XPAR_XRFDC_0_ADC2_Band 0
#define XPAR_XRFDC_0_ADC_Slice20_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode20 2
#define XPAR_XRFDC_0_ADC_Slice21_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode21 2
#define XPAR_XRFDC_0_ADC_Slice22_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode22 2
#define XPAR_XRFDC_0_ADC_Slice23_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode23 2
#define XPAR_XRFDC_0_ADC_Data_Type20 0
#define XPAR_XRFDC_0_ADC_Data_Width20 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode20 0
#define XPAR_XRFDC_0_ADC_Fifo20_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type20 3
#define XPAR_XRFDC_0_ADC_Data_Type21 0
#define XPAR_XRFDC_0_ADC_Data_Width21 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode21 0
#define XPAR_XRFDC_0_ADC_Fifo21_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type21 3
#define XPAR_XRFDC_0_ADC_Data_Type22 0
#define XPAR_XRFDC_0_ADC_Data_Width22 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode22 0
#define XPAR_XRFDC_0_ADC_Fifo22_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type22 3
#define XPAR_XRFDC_0_ADC_Data_Type23 0
#define XPAR_XRFDC_0_ADC_Data_Width23 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode23 0
#define XPAR_XRFDC_0_ADC_Fifo23_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type23 3
#define XPAR_XRFDC_0_ADC3_Enable 0
#define XPAR_XRFDC_0_ADC3_PLL_Enable 0
#define XPAR_XRFDC_0_ADC3_Sampling_Rate 2.0
#define XPAR_XRFDC_0_ADC3_Refclk_Freq 2000.000
#define XPAR_XRFDC_0_ADC3_Fabric_Freq 0.0
#define XPAR_XRFDC_0_ADC3_FBDIV 10
#define XPAR_XRFDC_0_ADC3_OutDiv 2
#define XPAR_XRFDC_0_ADC3_Refclk_Div 1
#define XPAR_XRFDC_0_ADC3_Band 0
#define XPAR_XRFDC_0_ADC_Slice30_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode30 2
#define XPAR_XRFDC_0_ADC_Slice31_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode31 2
#define XPAR_XRFDC_0_ADC_Slice32_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode32 2
#define XPAR_XRFDC_0_ADC_Slice33_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Mode33 2
#define XPAR_XRFDC_0_ADC_Data_Type30 0
#define XPAR_XRFDC_0_ADC_Data_Width30 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode30 0
#define XPAR_XRFDC_0_ADC_Fifo30_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type30 3
#define XPAR_XRFDC_0_ADC_Data_Type31 0
#define XPAR_XRFDC_0_ADC_Data_Width31 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode31 0
#define XPAR_XRFDC_0_ADC_Fifo31_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type31 3
#define XPAR_XRFDC_0_ADC_Data_Type32 0
#define XPAR_XRFDC_0_ADC_Data_Width32 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode32 0
#define XPAR_XRFDC_0_ADC_Fifo32_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type32 3
#define XPAR_XRFDC_0_ADC_Data_Type33 0
#define XPAR_XRFDC_0_ADC_Data_Width33 8
#define XPAR_XRFDC_0_ADC_Decimation_Mode33 0
#define XPAR_XRFDC_0_ADC_Fifo33_Enable 0
#define XPAR_XRFDC_0_ADC_Mixer_Type33 3


/******************************************************************/

/* Xilinx RFdc Device Name */
#define XPAR_XRFDC_0_DEV_NAME "a0000000.usp_rf_data_converter"

/******************************************************************/

/* Definitions for driver RTCPSU */
#define XPAR_XRTCPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSU_RTC */
#define XPAR_PSU_RTC_DEVICE_ID 0
#define XPAR_PSU_RTC_BASEADDR 0xFFA60000
#define XPAR_PSU_RTC_HIGHADDR 0xFFA6FFFF


/******************************************************************/

/* Canonical definitions for peripheral PSU_RTC */
#define XPAR_XRTCPSU_0_DEVICE_ID XPAR_PSU_RTC_DEVICE_ID
#define XPAR_XRTCPSU_0_BASEADDR 0xFFA60000
#define XPAR_XRTCPSU_0_HIGHADDR 0xFFA6FFFF


/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PSU_ACPU_GIC */
#define XPAR_PSU_ACPU_GIC_DEVICE_ID 0U
#define XPAR_PSU_ACPU_GIC_BASEADDR 0xF9020000U
#define XPAR_PSU_ACPU_GIC_HIGHADDR 0xF9020FFFU
#define XPAR_PSU_ACPU_GIC_DIST_BASEADDR 0xF9010000U


/******************************************************************/

/* Canonical definitions for peripheral PSU_ACPU_GIC */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF9020000U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF9020FFFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF9010000U


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PSU_SD_1 */
#define XPAR_PSU_SD_1_DEVICE_ID 0
#define XPAR_PSU_SD_1_BASEADDR 0xFF170000
#define XPAR_PSU_SD_1_HIGHADDR 0xFF17FFFF
#define XPAR_PSU_SD_1_SDIO_CLK_FREQ_HZ 187498123
#define XPAR_PSU_SD_1_HAS_CD 1
#define XPAR_PSU_SD_1_HAS_WP 0
#define XPAR_PSU_SD_1_BUS_WIDTH 8
#define XPAR_PSU_SD_1_MIO_BANK 1
#define XPAR_PSU_SD_1_HAS_EMIO 0


/******************************************************************/

#define XPAR_PSU_SD_1_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSU_SD_1 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PSU_SD_1_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xFF170000
#define XPAR_XSDPS_0_HIGHADDR 0xFF17FFFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 187498123
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 0
#define XPAR_XSDPS_0_BUS_WIDTH 8
#define XPAR_XSDPS_0_MIO_BANK 1
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver SYSMONPSU */
#define XPAR_XSYSMONPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSU_AMS */
#define XPAR_PSU_AMS_DEVICE_ID 0
#define XPAR_PSU_AMS_BASEADDR 0xFFA50000
#define XPAR_PSU_AMS_HIGHADDR 0xFFA5FFFF


/******************************************************************/

#define XPAR_PSU_AMS_REF_FREQMHZ 49.999500
/* Canonical definitions for peripheral PSU_AMS */
#define XPAR_XSYSMONPSU_0_DEVICE_ID XPAR_PSU_AMS_DEVICE_ID
#define XPAR_XSYSMONPSU_0_BASEADDR 0xFFA50000
#define XPAR_XSYSMONPSU_0_HIGHADDR 0xFFA5FFFF


/******************************************************************/

#define XPAR_XSYSMONPSU_0_REF_FREQMHZ 49.999500
/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 12U

/* Definitions for peripheral PSU_TTC_0 */
#define XPAR_PSU_TTC_0_DEVICE_ID 0U
#define XPAR_PSU_TTC_0_BASEADDR 0XFF110000U
#define XPAR_PSU_TTC_0_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_1_DEVICE_ID 1U
#define XPAR_PSU_TTC_1_BASEADDR 0XFF110004U
#define XPAR_PSU_TTC_1_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_2_DEVICE_ID 2U
#define XPAR_PSU_TTC_2_BASEADDR 0XFF110008U
#define XPAR_PSU_TTC_2_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_2_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSU_TTC_1 */
#define XPAR_PSU_TTC_3_DEVICE_ID 3U
#define XPAR_PSU_TTC_3_BASEADDR 0XFF120000U
#define XPAR_PSU_TTC_3_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_3_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_4_DEVICE_ID 4U
#define XPAR_PSU_TTC_4_BASEADDR 0XFF120004U
#define XPAR_PSU_TTC_4_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_4_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_5_DEVICE_ID 5U
#define XPAR_PSU_TTC_5_BASEADDR 0XFF120008U
#define XPAR_PSU_TTC_5_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_5_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSU_TTC_2 */
#define XPAR_PSU_TTC_6_DEVICE_ID 6U
#define XPAR_PSU_TTC_6_BASEADDR 0XFF130000U
#define XPAR_PSU_TTC_6_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_6_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_7_DEVICE_ID 7U
#define XPAR_PSU_TTC_7_BASEADDR 0XFF130004U
#define XPAR_PSU_TTC_7_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_7_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_8_DEVICE_ID 8U
#define XPAR_PSU_TTC_8_BASEADDR 0XFF130008U
#define XPAR_PSU_TTC_8_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_8_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSU_TTC_3 */
#define XPAR_PSU_TTC_9_DEVICE_ID 9U
#define XPAR_PSU_TTC_9_BASEADDR 0XFF140000U
#define XPAR_PSU_TTC_9_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_9_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_10_DEVICE_ID 10U
#define XPAR_PSU_TTC_10_BASEADDR 0XFF140004U
#define XPAR_PSU_TTC_10_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_10_TTC_CLK_CLKSRC 0U
#define XPAR_PSU_TTC_11_DEVICE_ID 11U
#define XPAR_PSU_TTC_11_BASEADDR 0XFF140008U
#define XPAR_PSU_TTC_11_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_PSU_TTC_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Canonical definitions for peripheral PSU_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PSU_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xFF110000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PSU_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xFF110004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PSU_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xFF110008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSU_TTC_1 */
#define XPAR_XTTCPS_3_DEVICE_ID XPAR_PSU_TTC_3_DEVICE_ID
#define XPAR_XTTCPS_3_BASEADDR 0xFF120000U
#define XPAR_XTTCPS_3_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_3_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_4_DEVICE_ID XPAR_PSU_TTC_4_DEVICE_ID
#define XPAR_XTTCPS_4_BASEADDR 0xFF120004U
#define XPAR_XTTCPS_4_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_4_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_5_DEVICE_ID XPAR_PSU_TTC_5_DEVICE_ID
#define XPAR_XTTCPS_5_BASEADDR 0xFF120008U
#define XPAR_XTTCPS_5_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_5_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSU_TTC_2 */
#define XPAR_XTTCPS_6_DEVICE_ID XPAR_PSU_TTC_6_DEVICE_ID
#define XPAR_XTTCPS_6_BASEADDR 0xFF130000U
#define XPAR_XTTCPS_6_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_6_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_7_DEVICE_ID XPAR_PSU_TTC_7_DEVICE_ID
#define XPAR_XTTCPS_7_BASEADDR 0xFF130004U
#define XPAR_XTTCPS_7_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_7_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_8_DEVICE_ID XPAR_PSU_TTC_8_DEVICE_ID
#define XPAR_XTTCPS_8_BASEADDR 0xFF130008U
#define XPAR_XTTCPS_8_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_8_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSU_TTC_3 */
#define XPAR_XTTCPS_9_DEVICE_ID XPAR_PSU_TTC_9_DEVICE_ID
#define XPAR_XTTCPS_9_BASEADDR 0xFF140000U
#define XPAR_XTTCPS_9_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_9_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_10_DEVICE_ID XPAR_PSU_TTC_10_DEVICE_ID
#define XPAR_XTTCPS_10_BASEADDR 0xFF140004U
#define XPAR_XTTCPS_10_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_10_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_11_DEVICE_ID XPAR_PSU_TTC_11_DEVICE_ID
#define XPAR_XTTCPS_11_BASEADDR 0xFF140008U
#define XPAR_XTTCPS_11_TTC_CLK_FREQ_HZ 100000000U
#define XPAR_XTTCPS_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 2

/* Definitions for peripheral PSU_UART_0 */
#define XPAR_PSU_UART_0_DEVICE_ID 0
#define XPAR_PSU_UART_0_BASEADDR 0xFF000000
#define XPAR_PSU_UART_0_HIGHADDR 0xFF00FFFF
#define XPAR_PSU_UART_0_UART_CLK_FREQ_HZ 99999001
#define XPAR_PSU_UART_0_HAS_MODEM 0


/* Definitions for peripheral PSU_UART_1 */
#define XPAR_PSU_UART_1_DEVICE_ID 1
#define XPAR_PSU_UART_1_BASEADDR 0xFF010000
#define XPAR_PSU_UART_1_HIGHADDR 0xFF01FFFF
#define XPAR_PSU_UART_1_UART_CLK_FREQ_HZ 99999001
#define XPAR_PSU_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PSU_UART_0 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PSU_UART_0_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xFF000000
#define XPAR_XUARTPS_0_HIGHADDR 0xFF00FFFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 99999001
#define XPAR_XUARTPS_0_HAS_MODEM 0

/* Canonical definitions for peripheral PSU_UART_1 */
#define XPAR_XUARTPS_1_DEVICE_ID XPAR_PSU_UART_1_DEVICE_ID
#define XPAR_XUARTPS_1_BASEADDR 0xFF010000
#define XPAR_XUARTPS_1_HIGHADDR 0xFF01FFFF
#define XPAR_XUARTPS_1_UART_CLK_FREQ_HZ 99999001
#define XPAR_XUARTPS_1_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPSU */
#define XPAR_XUSBPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSU_USB_XHCI_0 */
#define XPAR_PSU_USB_XHCI_0_DEVICE_ID 0
#define XPAR_PSU_USB_XHCI_0_BASEADDR 0xFE200000
#define XPAR_PSU_USB_XHCI_0_HIGHADDR 0xFE20FFFF


/******************************************************************/

#define XPAR_PSU_USB_XHCI_0_IS_CACHE_COHERENT 0
#define XPAR_PSU_USB_XHCI_0_SUPER_SPEED 1
/* Canonical definitions for peripheral PSU_USB_XHCI_0 */
#define XPAR_XUSBPSU_0_DEVICE_ID XPAR_PSU_USB_XHCI_0_DEVICE_ID
#define XPAR_XUSBPSU_0_BASEADDR 0xFE200000
#define XPAR_XUSBPSU_0_HIGHADDR 0xFE20FFFF


/******************************************************************/

/* Definitions for driver WDTPS */
#define XPAR_XWDTPS_NUM_INSTANCES 2

/* Definitions for peripheral PSU_WDT_0 */
#define XPAR_PSU_WDT_0_DEVICE_ID 0
#define XPAR_PSU_WDT_0_BASEADDR 0xFF150000
#define XPAR_PSU_WDT_0_HIGHADDR 0xFF15FFFF
#define XPAR_PSU_WDT_0_WDT_CLK_FREQ_HZ 99999001


/* Definitions for peripheral PSU_WDT_1 */
#define XPAR_PSU_WDT_1_DEVICE_ID 1
#define XPAR_PSU_WDT_1_BASEADDR 0xFD4D0000
#define XPAR_PSU_WDT_1_HIGHADDR 0xFD4DFFFF
#define XPAR_PSU_WDT_1_WDT_CLK_FREQ_HZ 99999001


/******************************************************************/

/* Canonical definitions for peripheral PSU_WDT_0 */
#define XPAR_XWDTPS_0_DEVICE_ID XPAR_PSU_WDT_0_DEVICE_ID
#define XPAR_XWDTPS_0_BASEADDR 0xFF150000
#define XPAR_XWDTPS_0_HIGHADDR 0xFF15FFFF
#define XPAR_XWDTPS_0_WDT_CLK_FREQ_HZ 99999001

/* Canonical definitions for peripheral PSU_WDT_1 */
#define XPAR_XWDTPS_1_DEVICE_ID XPAR_PSU_WDT_1_DEVICE_ID
#define XPAR_XWDTPS_1_BASEADDR 0xFD4D0000
#define XPAR_XWDTPS_1_HIGHADDR 0xFD4DFFFF
#define XPAR_XWDTPS_1_WDT_CLK_FREQ_HZ 99999001


/******************************************************************/

/* Definitions for driver ZDMA */
#define XPAR_XZDMA_NUM_INSTANCES 16

/* Definitions for peripheral PSU_ADMA_0 */
#define XPAR_PSU_ADMA_0_DEVICE_ID 0
#define XPAR_PSU_ADMA_0_BASEADDR 0xFFA80000
#define XPAR_PSU_ADMA_0_DMA_MODE 1
#define XPAR_PSU_ADMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_PSU_ADMA_0_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_1 */
#define XPAR_PSU_ADMA_1_DEVICE_ID 1
#define XPAR_PSU_ADMA_1_BASEADDR 0xFFA90000
#define XPAR_PSU_ADMA_1_DMA_MODE 1
#define XPAR_PSU_ADMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_PSU_ADMA_1_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_2 */
#define XPAR_PSU_ADMA_2_DEVICE_ID 2
#define XPAR_PSU_ADMA_2_BASEADDR 0xFFAA0000
#define XPAR_PSU_ADMA_2_DMA_MODE 1
#define XPAR_PSU_ADMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_PSU_ADMA_2_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_3 */
#define XPAR_PSU_ADMA_3_DEVICE_ID 3
#define XPAR_PSU_ADMA_3_BASEADDR 0xFFAB0000
#define XPAR_PSU_ADMA_3_DMA_MODE 1
#define XPAR_PSU_ADMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_PSU_ADMA_3_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_4 */
#define XPAR_PSU_ADMA_4_DEVICE_ID 4
#define XPAR_PSU_ADMA_4_BASEADDR 0xFFAC0000
#define XPAR_PSU_ADMA_4_DMA_MODE 1
#define XPAR_PSU_ADMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_PSU_ADMA_4_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_5 */
#define XPAR_PSU_ADMA_5_DEVICE_ID 5
#define XPAR_PSU_ADMA_5_BASEADDR 0xFFAD0000
#define XPAR_PSU_ADMA_5_DMA_MODE 1
#define XPAR_PSU_ADMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_PSU_ADMA_5_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_6 */
#define XPAR_PSU_ADMA_6_DEVICE_ID 6
#define XPAR_PSU_ADMA_6_BASEADDR 0xFFAE0000
#define XPAR_PSU_ADMA_6_DMA_MODE 1
#define XPAR_PSU_ADMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_PSU_ADMA_6_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_ADMA_7 */
#define XPAR_PSU_ADMA_7_DEVICE_ID 7
#define XPAR_PSU_ADMA_7_BASEADDR 0xFFAF0000
#define XPAR_PSU_ADMA_7_DMA_MODE 1
#define XPAR_PSU_ADMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_PSU_ADMA_7_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_0 */
#define XPAR_PSU_GDMA_0_DEVICE_ID 8
#define XPAR_PSU_GDMA_0_BASEADDR 0xFD500000
#define XPAR_PSU_GDMA_0_DMA_MODE 0
#define XPAR_PSU_GDMA_0_HIGHADDR 0xFD50FFFF
#define XPAR_PSU_GDMA_0_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_1 */
#define XPAR_PSU_GDMA_1_DEVICE_ID 9
#define XPAR_PSU_GDMA_1_BASEADDR 0xFD510000
#define XPAR_PSU_GDMA_1_DMA_MODE 0
#define XPAR_PSU_GDMA_1_HIGHADDR 0xFD51FFFF
#define XPAR_PSU_GDMA_1_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_2 */
#define XPAR_PSU_GDMA_2_DEVICE_ID 10
#define XPAR_PSU_GDMA_2_BASEADDR 0xFD520000
#define XPAR_PSU_GDMA_2_DMA_MODE 0
#define XPAR_PSU_GDMA_2_HIGHADDR 0xFD52FFFF
#define XPAR_PSU_GDMA_2_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_3 */
#define XPAR_PSU_GDMA_3_DEVICE_ID 11
#define XPAR_PSU_GDMA_3_BASEADDR 0xFD530000
#define XPAR_PSU_GDMA_3_DMA_MODE 0
#define XPAR_PSU_GDMA_3_HIGHADDR 0xFD53FFFF
#define XPAR_PSU_GDMA_3_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_4 */
#define XPAR_PSU_GDMA_4_DEVICE_ID 12
#define XPAR_PSU_GDMA_4_BASEADDR 0xFD540000
#define XPAR_PSU_GDMA_4_DMA_MODE 0
#define XPAR_PSU_GDMA_4_HIGHADDR 0xFD54FFFF
#define XPAR_PSU_GDMA_4_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_5 */
#define XPAR_PSU_GDMA_5_DEVICE_ID 13
#define XPAR_PSU_GDMA_5_BASEADDR 0xFD550000
#define XPAR_PSU_GDMA_5_DMA_MODE 0
#define XPAR_PSU_GDMA_5_HIGHADDR 0xFD55FFFF
#define XPAR_PSU_GDMA_5_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_6 */
#define XPAR_PSU_GDMA_6_DEVICE_ID 14
#define XPAR_PSU_GDMA_6_BASEADDR 0xFD560000
#define XPAR_PSU_GDMA_6_DMA_MODE 0
#define XPAR_PSU_GDMA_6_HIGHADDR 0xFD56FFFF
#define XPAR_PSU_GDMA_6_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSU_GDMA_7 */
#define XPAR_PSU_GDMA_7_DEVICE_ID 15
#define XPAR_PSU_GDMA_7_BASEADDR 0xFD570000
#define XPAR_PSU_GDMA_7_DMA_MODE 0
#define XPAR_PSU_GDMA_7_HIGHADDR 0xFD57FFFF
#define XPAR_PSU_GDMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PSU_ADMA_0_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_1_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_2_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_3_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_4_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_5_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_6_IS_CACHE_COHERENT 0
#define XPAR_PSU_ADMA_7_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_0_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_1_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_2_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_3_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_4_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_5_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_6_IS_CACHE_COHERENT 0
#define XPAR_PSU_GDMA_7_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSU_ADMA_0 */
#define XPAR_XZDMA_0_DEVICE_ID XPAR_PSU_ADMA_0_DEVICE_ID
#define XPAR_XZDMA_0_BASEADDR 0xFFA80000
#define XPAR_XZDMA_0_DMA_MODE 1
#define XPAR_XZDMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_XZDMA_0_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_1 */
#define XPAR_XZDMA_1_DEVICE_ID XPAR_PSU_ADMA_1_DEVICE_ID
#define XPAR_XZDMA_1_BASEADDR 0xFFA90000
#define XPAR_XZDMA_1_DMA_MODE 1
#define XPAR_XZDMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_XZDMA_1_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_2 */
#define XPAR_XZDMA_2_DEVICE_ID XPAR_PSU_ADMA_2_DEVICE_ID
#define XPAR_XZDMA_2_BASEADDR 0xFFAA0000
#define XPAR_XZDMA_2_DMA_MODE 1
#define XPAR_XZDMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_XZDMA_2_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_3 */
#define XPAR_XZDMA_3_DEVICE_ID XPAR_PSU_ADMA_3_DEVICE_ID
#define XPAR_XZDMA_3_BASEADDR 0xFFAB0000
#define XPAR_XZDMA_3_DMA_MODE 1
#define XPAR_XZDMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_XZDMA_3_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_4 */
#define XPAR_XZDMA_4_DEVICE_ID XPAR_PSU_ADMA_4_DEVICE_ID
#define XPAR_XZDMA_4_BASEADDR 0xFFAC0000
#define XPAR_XZDMA_4_DMA_MODE 1
#define XPAR_XZDMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_XZDMA_4_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_5 */
#define XPAR_XZDMA_5_DEVICE_ID XPAR_PSU_ADMA_5_DEVICE_ID
#define XPAR_XZDMA_5_BASEADDR 0xFFAD0000
#define XPAR_XZDMA_5_DMA_MODE 1
#define XPAR_XZDMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_XZDMA_5_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_6 */
#define XPAR_XZDMA_6_DEVICE_ID XPAR_PSU_ADMA_6_DEVICE_ID
#define XPAR_XZDMA_6_BASEADDR 0xFFAE0000
#define XPAR_XZDMA_6_DMA_MODE 1
#define XPAR_XZDMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_XZDMA_6_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_ADMA_7 */
#define XPAR_XZDMA_7_DEVICE_ID XPAR_PSU_ADMA_7_DEVICE_ID
#define XPAR_XZDMA_7_BASEADDR 0xFFAF0000
#define XPAR_XZDMA_7_DMA_MODE 1
#define XPAR_XZDMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_XZDMA_7_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_0 */
#define XPAR_XZDMA_8_DEVICE_ID XPAR_PSU_GDMA_0_DEVICE_ID
#define XPAR_XZDMA_8_BASEADDR 0xFD500000
#define XPAR_XZDMA_8_DMA_MODE 0
#define XPAR_XZDMA_8_HIGHADDR 0xFD50FFFF
#define XPAR_XZDMA_8_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_1 */
#define XPAR_XZDMA_9_DEVICE_ID XPAR_PSU_GDMA_1_DEVICE_ID
#define XPAR_XZDMA_9_BASEADDR 0xFD510000
#define XPAR_XZDMA_9_DMA_MODE 0
#define XPAR_XZDMA_9_HIGHADDR 0xFD51FFFF
#define XPAR_XZDMA_9_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_2 */
#define XPAR_XZDMA_10_DEVICE_ID XPAR_PSU_GDMA_2_DEVICE_ID
#define XPAR_XZDMA_10_BASEADDR 0xFD520000
#define XPAR_XZDMA_10_DMA_MODE 0
#define XPAR_XZDMA_10_HIGHADDR 0xFD52FFFF
#define XPAR_XZDMA_10_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_3 */
#define XPAR_XZDMA_11_DEVICE_ID XPAR_PSU_GDMA_3_DEVICE_ID
#define XPAR_XZDMA_11_BASEADDR 0xFD530000
#define XPAR_XZDMA_11_DMA_MODE 0
#define XPAR_XZDMA_11_HIGHADDR 0xFD53FFFF
#define XPAR_XZDMA_11_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_4 */
#define XPAR_XZDMA_12_DEVICE_ID XPAR_PSU_GDMA_4_DEVICE_ID
#define XPAR_XZDMA_12_BASEADDR 0xFD540000
#define XPAR_XZDMA_12_DMA_MODE 0
#define XPAR_XZDMA_12_HIGHADDR 0xFD54FFFF
#define XPAR_XZDMA_12_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_5 */
#define XPAR_XZDMA_13_DEVICE_ID XPAR_PSU_GDMA_5_DEVICE_ID
#define XPAR_XZDMA_13_BASEADDR 0xFD550000
#define XPAR_XZDMA_13_DMA_MODE 0
#define XPAR_XZDMA_13_HIGHADDR 0xFD55FFFF
#define XPAR_XZDMA_13_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_6 */
#define XPAR_XZDMA_14_DEVICE_ID XPAR_PSU_GDMA_6_DEVICE_ID
#define XPAR_XZDMA_14_BASEADDR 0xFD560000
#define XPAR_XZDMA_14_DMA_MODE 0
#define XPAR_XZDMA_14_HIGHADDR 0xFD56FFFF
#define XPAR_XZDMA_14_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSU_GDMA_7 */
#define XPAR_XZDMA_15_DEVICE_ID XPAR_PSU_GDMA_7_DEVICE_ID
#define XPAR_XZDMA_15_BASEADDR 0xFD570000
#define XPAR_XZDMA_15_DMA_MODE 0
#define XPAR_XZDMA_15_HIGHADDR 0xFD57FFFF
#define XPAR_XZDMA_15_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#endif  /* end of protection macro */
