
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 5.2
 PARAMETER PROC_INSTANCE = mb_1_microblaze_1
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.3
 PARAMETER HW_INSTANCE = mb_1_microblaze_1
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_1_lmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PMOD_IO_Switch_IP
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = mb_1_mb1_switch
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = mb_1_mb_1_axi_iic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = mb_1_mb_1_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.1
 PARAMETER HW_INSTANCE = mb_1_mb_1_spi_0
END


